import React, { useRef, useState } from 'react';
import { BlockMath, InlineMath } from 'react-katex';
import SimplexCanvas from './SimplexCanvas';
import { KNOWLEDGE_BASE_DIRECTORY, MENU_SECTOR_LIST, TUTORIAL_SLIDER_CONFIG } from './matrixData';

const PROFILES=['Young Learner','Physicist','Mathematician'];
const VIEWS=['Clifford','Prime','Simplex','Cube'];
const labels={en:{tour:'The shared four-step tour',results:'Three result branches',matrix:'Language · audience · representation',note:'Educational visual toy model — not an established peer-reviewed physical theory.',lede:'The same visual journey adapts its language and explanatory depth for every audience. Use the controls below; every tour card and each result branch updates together.',open:'Open branch',step:'Step',active:'Active sector',activeNote:'Choose any of the nine nodes below. Its detailed explanation and visualization stay here, directly after the tour.',now:'Now exploring',directory:'Sector directory',viewing:'Viewing',viewNode:'View'},it:{tour:'Il tour condiviso in quattro passi',results:'Tre rami di risultati',matrix:'Lingua · pubblico · rappresentazione',note:'Modello visivo educativo — non una teoria fisica consolidata e sottoposta a peer review.',lede:'Lo stesso viaggio visivo adatta lingua e profondità esplicativa per ogni pubblico. Usa i controlli: ogni scheda del tour e ciascun ramo di risultati si aggiorna insieme.',open:'Apri il ramo',step:'Passo',active:'Settore attivo',activeNote:'Scegli uno dei nove nodi qui sotto. La spiegazione dettagliata e la visualizzazione rimangono qui, subito dopo il tour.',now:'In esplorazione',directory:'Elenco dei settori',viewing:'In visione',viewNode:'Apri'}};
export default function App(){
 const [lang,setLang]=useState('en'),[profile,setProfile]=useState('Young Learner'),[view,setView]=useState('Clifford'),[step,setStep]=useState(0),[sector,setSector]=useState('Sector_EM_Maxwell');
 const resultRef = useRef(null);
 const t=labels[lang], record=KNOWLEDGE_BASE_DIRECTORY[`${sector}_${lang}_${profile}`], slides=TUTORIAL_SLIDER_CONFIG[lang][profile], selected=MENU_SECTOR_LIST.find(x=>x.id===sector);
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span>01</span> EIGHT SWITCHES</a></header>
  <section className="hero" id="top"><p className="eyebrow">Interactive research atlas · 2 × 3 × 4 presentation matrix</p><h1>{t.tour}</h1><p className="lede">{t.lede}</p><p className="disclosure">{t.note}</p></section>
  <ControlBar lang={lang} setLang={setLang} profile={profile} setProfile={setProfile} view={view} setView={setView}/>
  <section className="tour"><div className="tour-copy"><p className="eyebrow">{t.step.toUpperCase()} {step+1} / 4 · {profile.toUpperCase()}</p><h2>{slides[step].title}</h2><p>{slides[step].desc}</p><p className="cue">{view} lens: {telemetry(record,view)}</p><div className="steps">{slides.map((x,i)=><button onClick={()=>setStep(i)} className={i===step?'active':''} key={x.step}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="diagram"><SimplexCanvas step={step} activeView={view} sector={sector}/><span>{t.matrix}: {lang.toUpperCase()} · {profile} · {view}</span></div></section>
  <section className="explorer-intro"><p className="eyebrow">{t.results.toUpperCase()}</p><h2>{t.active}</h2><p>{t.activeNote}</p></section>
  <section className="result active-result" ref={resultRef} tabIndex="-1"><article className="paper"><p className="eyebrow">{t.now.toUpperCase()} · {selected.category.toUpperCase()} · {view.toUpperCase()} VIEW</p><h2>{record.title}</h2><p>{record.desc}</p><ResultFormal sector={sector} profile={profile} lang={lang} record={record}/></article><aside className="proof-map"><p className="eyebrow">ACTIVE SECTOR VISUALIZATION</p><SimplexCanvas step={3} activeView={view} sector={sector}/><div className="view-pills">{VIEWS.map(v=><button onClick={()=>setView(v)} className={v===view?'active':''} key={v}>{v}: {telemetry(record,v)}</button>)}</div></aside></section>
  <SectorNavigator lang={lang} profile={profile} t={t} sector={sector} setSector={setSector} resultRef={resultRef}/>
  <ChatPanel lang={lang} profile={profile}/><footer><span>Clifford · Prime · Simplex · Cube</span><span>{t.note}</span></footer>
 </main>
}
function SectorNavigator({lang,profile,t,sector,setSector,resultRef}){const groups=MENU_SECTOR_LIST.reduce((all,item)=>{(all[item.category]??=[]).push(item);return all;},{});return <section className="sector-navigator"><p className="eyebrow">{t.directory.toUpperCase()} · 9 NODES</p><div className="sector-groups">{Object.entries(groups).map(([category,items])=><div className="sector-group" key={category}><h3>{category}</h3>{items.map(item=>{const data=KNOWLEDGE_BASE_DIRECTORY[`${item.id}_${lang}_${profile}`];const active=item.id===sector;return <button className={active?'active':''} aria-pressed={active} onClick={()=>{setSector(item.id);requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}} key={item.id}><span>{data.title}</span><small>{active?t.viewing:t.viewNode}</small></button>})}</div>)}</div></section>}
function ControlBar({lang,setLang,profile,setProfile,view,setView}){return <section className="controls" aria-label="Presentation controls"><div className="control-title"><span>Presentation matrix</span><small>{lang.toUpperCase()} · {profile} · {view}</small></div><div className="control-group language-group"><p>LANGUAGE</p><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button><button className={lang==='it'?'active':''} onClick={()=>setLang('it')}>IT</button></div><div className="control-group audience-group"><p>AUDIENCE</p>{PROFILES.map(x=><button className={profile===x?'active':''} onClick={()=>setProfile(x)} key={x}>{x==='Young Learner'?'Learner':x==='Physicist'?'Physics':'Math'}</button>)}</div><div className="control-group lens-group"><p>LENS</p>{VIEWS.map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x}</button>)}</div></section>}
function telemetry(record,view){return view==='Clifford'?record.grade:view==='Prime'?`Multiplicity [${record.coordinate}]`:view==='Simplex'?record.simplex:record.cube}
function ResultFormal({ sector, profile, lang, record }) {
 if (profile === 'Young Learner') return null;
 const it=lang==='it';
 const proofs={
  Sector_Vacuum_Origin:[it?"Teorema I: L'Origine Scalare del Vuoto":"Theorem I: The Trivial Scalar Vacuum Origin",it?"Il punto zero della griglia stabilisce l’elemento identità moltiplicativo scalare, da cui si diramano le sotto-algebre.":"The grid zero-point establishes the pure scalar multiplicative identity element, from which all sub-algebras branch.",String.raw`\text{Grid Level: }[B+F=0,\,B-F=0]\implies\text{Cl}(0,0)\cong\mathbb{R}`,it?'Isomorfismo del Sotto-Spazio Radicale:':'Radical Subspace Isomorphism:',String.raw`\mathbf1\in\text{Cl}(4,4,0)_0\quad\text{where}\quad\langle\mathbf1\cdot x\rangle_0=x_0`],
  Sector_Inject_Base_Real:[it?"Teorema II: L'Iniettore Reale di Base":"Theorem II: The Base Real Vector Injector",it?'L’iniezione di un singolo bit spaziale positivo mappa un vettore reale sulla varietà macroscopica.':'The injection of a single positive spatial bit maps a real vector onto the macroscopic manifold.',String.raw`\text{Grid Level: }[B+F=1,\,B-F=+1]\implies\text{Cl}(1,0)\cong\mathbb{R}\oplus\mathbb{R}`,it?'Generatore di Spostamento della Griglia:':'Lattice Displacement Generator:',String.raw`\Pi_{BF}(e_1)=0\quad\land\quad\sigma_{\pm}(e_1)=+1\implies e_1^2=+1`],
  Sector_Inject_Fiber_Clock:[it?"Teorema III: L'Iniettore della Fibra Complessa":"Theorem III: The Internal Complex Fiber Injector",it?'Un singolo bit temporale negativo nella fibra agisce come orologio di fase immaginario.':'A single negative time-like bit embedded in the fiber acts as an imaginary phase clock.',String.raw`\text{Grid Level: }[B+F=1,\,B-F=-1]\implies\text{Cl}(0,1)\cong\mathbb{C}`,it?'Generatore della Fase di Gauge:':'Internal Gauge Phase Rotor:',String.raw`\Pi_{BF}(f_1)=1\quad\land\quad\sigma_{\pm}(f_1)=-1\implies f_1^2=-1`],
  Sector_EM_Maxwell:[it?'Teorema IV: Il Campo di Maxwell':'Theorem IV: The Maxwell Curvature Bivector',it?'Le quattro equazioni di campo si contraggono in un unico enunciato di derivata geometrica.':'The four classical field equations collapse into a single geometric derivative statement.',String.raw`\nabla F=J\quad\text{where}\quad F=\mathbf{E}+I\mathbf{B}\in\text{Cl}(6,2)`,it?"Invarianza dei Canali dell'Orologio Aritmetico:":'Arithmetic Phase Clock Invariance:',String.raw`\nabla F=(\partial_t+\nabla)\cdot(\mathbf{E}+I\mathbf{B})=J\implies\text{Channels }|n|=85`],
  Sector_Gravity_Strain:[it?'Teorema V: Lo Sforzo di Gravità della Teoria di Gauge':'Theorem V: Gauge Theory Gravity & Lattice Strain',it?'La gravità è mappata come gradiente di traslazione che inclina gli assi spaziali della griglia.':'Gravity is mapped as a localized translation gradient that skews the spatial grid axes.',String.raw`\mathbf{S}_{AB}(x)=h_A^\mu(x)h_B^\nu(x)\eta_{\mu\nu}-\eta_{AB}`,it?'Contrazione dello Sforzo di Noether:':'Canonical Noether Strain Contraction:',String.raw`T^{\mu\nu}\implies\Delta V_{\text{cell}}\propto\text{Tr}(\mathbf{S}_{AB})`],
  Sector_Quaternionic_Base:[it?'Teorema VI: Superficie di Spazio Matrice Reale':'Theorem VI: Real 2D Matrix Surface Mesh',it?"La coordinata di base mappa due assi di tipo spazio, generando l'algebra delle matrici reali 2x2 con divisori dello zero.":'The base coordinate maps two space-like axes, generating the algebra of real 2x2 matrices containing zero divisors.',String.raw`\text{Grid Level: }[B+F=2,\,B-F=+2]\implies\text{Cl}(2,0)\cong M_2(\mathbb{R})`,it?'Generazione della Struttura dello Spazio di Base:':'Base Surface Space Generation:',String.raw`e_1^2=+1,\quad e_2^2=+1\implies(e_1e_2)^2=-1`],
  Sector_Quaternionic_Fiber:[it?'Teorema VII: Spazio di Fase Elettrodebole SU(2)':'Theorem VII: Weak Isospin SU(2) Compact Fiber Phase',it?'Le trasformazioni di gauge deboli non abeliane nascono dalla struttura quaternionica compatta della fibra senza divisori dello zero.':'Non-abelian weak gauge fields arise from the compact quaternionic fiber phase space without zero divisors.',String.raw`\text{Grid Level: }[B+F=2,\,B-F=-2]\implies\text{Cl}(0,2)\cong\mathbb{H}`,it?'Generazione dei Campi di Gauge Spinoriali:':'Spinor Gauge Field Generation:',String.raw`i^2=j^2=k^2=ijk=-1\implies\Psi\in\text{SU}(2)_L`],
  Sector_Baryon_Conservation:[it?'Teorema VIII: Conservazione del Numero Barionico':'Theorem VIII: Topological Baryon Stability',it?'La stabilità del protone emerge come vincolo di avvolgimento topologico rigido sui cicli del piano di Fano.':'Proton stability is represented as a rigid topological winding restriction over an embedded Fano plane.',String.raw`\text{Grid Level: }[B+F=8,\,B-F=+2]\implies\text{Cl}(5,1)\cong M_4(\mathbb{H})`,it?'Indice Invariante del Ciclo del Piano di Fano:':'Fano Plane Cyclic Winding Invariant:',String.raw`\nu_B\equiv\frac{\nu_7\pmod3}{3}\implies[\mathcal{D}_\mu^{(3,5)},\mathcal{I}_7]\cap\mathcal{I}_0=\emptyset`],
  Sector_Electroweak_Unified:[it?'Teorema IX: Il Settore di Gauge Elettrodebole':'Theorem IX: The Saturated Electroweak Sector',it?'La frazione di impacchettamento 4/17 è una convenzione interna del modello visivo.':'The 4/17 packing fraction is an internal convention of this visual toy model.',String.raw`\sin^2\theta_W\equiv\frac{|\mathcal{N}_L|}{|\mathcal{N}|}=\frac4{17}\approx0.23529`,it?'Incrocio dei Canali della Corrente Neutra:':'Neutral Current Channel Crossing Constraints:',String.raw`\mathcal{N}_L=\{e_{ij}\in\mathcal{N}\mid\Pi_{BF}(e_{ij})=0\land\chi_{LR}(e_{ij})=L\}\implies|\mathcal{N}_L|=4`],
  Sector_Vacuum_Mass_Generation:[it?'Teorema X: Inversione Scalare del Vuoto':'Theorem X: Identity Scalar Vacuum Inversion',it?'Il neutrino sterile e il campo di Higgs sono configurazioni isomorfe dello stesso nucleo scalare.':'The Sterile Neutrino and the active Higgs-field operator are toy-model configurations of the same scalar identity.',String.raw`\mathcal{M}(\mathbf{\Phi}_H\cdot\mathbf1)\equiv\psi_\nu`,it?'Mappatura della Riflessione Iper-Superficiale:':'Hyper-surface Reflection Auto-mapping:',String.raw`x\mapsto\operatorname{NOT}(x)`],
  Sector_GUT_Junction:[it?'Teorema XI: Il Checkpoint di Saturazione Primorale':'Theorem XI: The Primorial Saturation Junction',it?'Le simmetrie di gauge si fondono al prodotto primorale 210 nella convenzione del portale.':'Gauge tracks intersect at the primorial product 210 in the portal convention.',String.raw`\mathbf{\Omega}_{\text{GUT}}=e_1\wedge e_2\wedge f_1\wedge e_3\implies\mathbf{\Omega}_{\text{GUT}}^2=-1`,it?"Frazione Sotto-Blocco dell'Iper-Reticolo:":'Hyper-lattice Sub-block Packing Fraction:',String.raw`\text{Faces}_{\text{7-Simplex}}=70\longleftrightarrow\text{Tesseracts}_{\text{Octeract}}=1120`],
  Sector_Cosmic_Horizon:[it?"Teorema XII: Confine dell'Orizzonte Pseudoscalare Massimo":'Theorem XII: The Maximal Pseudoscalar Horizon',it?"La saturazione dell'elemento pseudoscalare impone una chiusura geometrica del modello.":'Saturation of the maximal pseudoscalar element represents a portal boundary-reset convention.',String.raw`I_8=\gamma_1\gamma_2\gamma_3\gamma_4\gamma_5\gamma_6\gamma_7\gamma_8\implies I_8^2=-1`,it?"Limite Cosmico dell'Orizzonte di Hubble:":'Macroscopic Hubble Horizon Limit:',String.raw`\Lambda_{\text{Master}}=[1,1,1,1]\otimes[1,1,1,1]\implies D_H=8`],
  Sector_Trivector_Base:[it?'Teorema XIII: Volume Spaziale Macroscopico':'Theorem XIII: Macroscopic Spatial Volume Pseudoscalar',it?"L'elemento orientatore tridimensionale è formalizzato dal prodotto esterno di tre vettori spaziali ortogonali.":'The three-dimensional orienting element is formalized through the exterior product of three mutually orthogonal spatial basis vectors.',String.raw`\text{Cl}(3,0)\implies I_{3D}=\gamma_1\wedge\gamma_2\wedge\gamma_3\quad\text{where}\quad I_{3D}^2=-1`,it?'Orientazione del volume:':'Volume orientation:',String.raw`\gamma_1\wedge\gamma_2\wedge\gamma_3`],
  Sector_Trivector_Quark:[it?'Teorema XIV: Vertice Quark-Gluone Asimmetrico':'Theorem XIV: Asymmetric Quark Core Geometry',it?'La carica frazionaria è rappresentata dalla ripartizione asimmetrica dei gradi tra la varietà macroscopica e la fibra quantistica interna.':'Fractional states emerge from the asymmetric grading distribution between the macroscopic manifold and internal quantum fiber.',String.raw`B=2,\,F=1\implies\nu_c\propto2/3`,it?'Indice di Avvolgimento Asimmetrico:':'Asymmetric Winding Number:',String.raw`\gcd(3^\alpha\cdot5^\beta,7)=1`],
  Sector_Trivector_Lepton:[it?'Teorema XV: Frame di Corrente Leptonica':'Theorem XV: Leptonic Current Coordinates',it?'Le traiettorie leptoniche usano un singolo asse reale proiettato su due piani complessi interni.':'Charged leptonic trajectories use a single real axis projected across two internal complex fiber phase planes.',String.raw`\text{Cl}(1,2)\cong M_2(\mathbb{C})\implies\text{Leptonic Current}`,it?'Accoppiamento della Corrente:':'Current Coupling Matrix:',String.raw`[B+F=3,\,B-F=-1]`],
  Sector_STA_Euclidean_Base:[it?'Teorema XVI: Spazio Quadridimensionale Euclideo':'Theorem XVI: Pure Euclidean 4D Base Manifold',it?'La varietà quadridimensionale spaziale pura è generata dal prodotto esterno di quattro vettori reali ortogonali.':'The pure four-dimensional spatial manifold is generated via four orthogonal real basis vectors.',String.raw`\text{Cl}(4,0)\implies\mathbf{\Omega}_{4D}=\gamma_1\wedge\gamma_2\wedge\gamma_3\wedge\gamma_4`,it?'Contenitore Spaziale Piatto:':'Flat Spatial Container:',String.raw`[B+F=4,\,B-F=+4]`],
  Sector_STA_Minkowski:[it?'Teorema XVII: Algebra dello Spazio-Tempo Relativistico':'Theorem XVII: Minkowski Spacetime Algebra',it?'La metrica di Minkowski sorge dalla segnatura di tre assi spaziali e un asse temporale interno.':'The Minkowski metric emerges from three spatial base axes and one time-like fiber parameter.',String.raw`\text{Cl}(3,1)\implies g_{\mu\nu}=\operatorname{diag}(1,1,1,-1)`,it?'Struttura del Cono di Luce:':'Light-Cone Vector Frame:',String.raw`(+,+,+,-)`],
  Sector_STA_Symmetric_Core:[it?'Teorema XVIII: Reticolo di Accoppiamento Simmetrico':'Theorem XVIII: Symmetric Electroweak Cross-Talk Core',it?'La giunzione simmetrica bilancia due dimensioni macroscopiche e due dimensioni di fibra di gauge.':'The symmetric core balances exactly two macroscopic base dimensions and two internal gauge fiber coordinates.',String.raw`\text{Cl}(2,2)\cong M_4(\mathbb{R})\implies\text{Symmetric Junction}`,it?'Incrocio Spazio-Fibra:':'Base-Fiber Balance Node:',String.raw`[B+F=4,\,B-F=0]`],
  Sector_STA_Fiber_Frame:[it?'Teorema XIX: Frame Invariante di Gauge Debole':'Theorem XIX: Weak Gauge Invariant Fiber Topology',it?'Il frame della fibra di gauge debole isola un singolo asse reale proiettato su tre assi temporali interni.':'The weak gauge fiber topology restricts one real base parameter across three internal time-like fiber metrics.',String.raw`\text{Cl}(1,3)\cong M_2(\mathbb{H})\implies\text{Weak Invariant}`,it?'Isolamento Chirale Sinistro:':'Left-Ideal Chiral Locking:',String.raw`\chi_{LR}=L\quad\text{at}\quad[B-F=-2]`],
  Sector_Row5_Base:[it?'Teorema XX: Struttura Spinoriale Complessificata':'Theorem XX: Complexified Pentavector Spinor Space',it?"L'estensione pseudoscalare introduce una coordinata complessa immaginaria che segrega gli ideali sinistri dalle invarianze destre.":'The pseudoscalar extension introduces an imaginary complex coordinate that segregates left-handed interacting ideals from right-handed sterile invariants.',String.raw`\text{Cl}(4,1)\cong\text{Cl}(4,0)\otimes\mathbb{C}\implies I_{5D}=\gamma_1\gamma_2\gamma_3\gamma_4\gamma_5`,it?'Asse della Violazione di Parità:':'Parity Violation Axis:',String.raw`[B+F=5,\,B-F=+3]`],
  Sector_Row6_Confinement:[it?'Teorema XXI: Connessione Esavettoriale del Colore':'Theorem XXI: Hexvector Holonomy & Confinement',it?"L'olonomia a 6 bit impone la chiusura topologica ciclica del flusso del colore sul volume del piano di Fano.":'The 6-bit holonomy enforces cyclic topological closure of color flux over Fano-plane volume elements.',String.raw`\text{Cl}(5,1)\cong M_4(\mathbb{H})\implies\oint_{\partial\mathcal{P}_3}\omega_c\equiv0\pmod7`,it?'Chiusura Ciclica del Colore:':'Cyclic Color Confinement:',String.raw`[B+F=6,\,B-F=+2]`],
  Sector_Row7_Mirror:[it?'Teorema XXII: Confine del Semipool Involutivo':'Theorem XXII: The Chiral Half-Pool Threshold',it?'Il semipool a 128 elementi segna la frontiera di inversione iper-superficiale della coniugazione di carica.':'The 128-element semipool bounds the inversion frontier mapping matter coordinates to antimatter complements.',String.raw`\text{Cl}(4,3)\cong M_8(\mathbb{R})\oplus M_8(\mathbb{R})\implies\dim(\mathcal{L}_0)=128`,it?"Flessione Antipodale dell'Ipercubo:":'Hypercube Antipodal Mapping:',String.raw`x\mapsto\operatorname{NOT}(x)\equiv\Gamma_{192}`],
  Sector_Open_Questions:[it?'Critica Formale: Limiti Strutturali del Modello':'Formal Critique: Structural Model Limitations',it?'Il modello rimane privo di un meccanismo continuo per calcolare la costante di accoppiamento dinamica e la rinormalizzazione.':'The model lacks a native differential mechanics engine to derive continuous coupling running or absolute mass scales.',String.raw`\lim_{\Delta h\to0}\mathbf{S}_{AB}(x)\neq\text{RGE Running Path}`,it?'Paradosso del Continuo della Griglia:':'Lattice Continuum Paradox:',String.raw`\text{Scaffold Incompleteness Invariant}`],
  Sector_Furey_Ledger:[it?'Capitolo I: Soluzioni Algebriche Invarianti per la Dr.ssa Furey':'Chapter I: Invariant Algebraic Solutions for Dr. Furey',it?'Mappatura delle catene di moltiplicazione di Furey e dei proiettori idempotenti nelle coordinate della nostra matrice.':"Mapping Furey's complex octonionic multiplication chains and Peirce idempotents into our 2D grid matrix coordinates.",String.raw`\mathbb{R}\mathbb{O}\cong\text{Cl}(6,0)\xrightarrow{\otimes\text{Cl}(2,0)}\text{Cl}(4,4,0)`,it?'Decomposizione degli Idempotenti di Peirce:':'Peirce Idempotent Structural Decomposition:',String.raw`\Psi_{\text{Gen }g}=\frac12(1\pm\Lambda_G)I_8\cdot\text{Cl}(4,4,0)\cdot e_{\text{Peirce}}` ]
 };
 const item=proofs[sector]||proofs.Sector_Vacuum_Origin;
 return <details className="formal-proof"><summary>{it?'Apri il teorema e la dimostrazione':'Open theorem and proof'}</summary><div className="theorem"><b>{item[0]}</b><p>{item[1]}</p><BlockMath math={item[2]}/><div className="lemma"><b>{item[3]}</b><BlockMath math={item[4]}/></div></div></details>;
}

function ChatPanel({lang,profile}){const [input,setInput]=useState('');const [answer,setAnswer]=useState('');const [loading,setLoading]=useState(false);async function ask(e){e.preventDefault();if(!input.trim()||loading)return;setLoading(true);setAnswer('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({spokenLang:lang,userProfile:profile,messages:[{role:'user',content:input}]})});if(!r.ok)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let text='',buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=done?'':lines.pop();for(const line of lines){if(!line.startsWith('data: ')||line.includes('[DONE]'))continue;try{const event=JSON.parse(line.slice(6));text+=event.type==='content_block_delta'?event.delta?.text||'':'';setAnswer(text)}catch{}}if(done)break}}catch{setAnswer(lang==='it'?'Il servizio chat non è disponibile.':'Chat is unavailable.')}finally{setLoading(false)}}return <section className="chat"><p className="eyebrow">CASCADE GUIDE · {profile.toUpperCase()}</p><h2>{lang==='it'?'Chiedi al modello':'Ask the model'}</h2><form onSubmit={ask}><input value={input} onChange={e=>setInput(e.target.value)} placeholder={lang==='it'?'Fai una domanda':'Ask a question'} maxLength="1000"/><button disabled={loading}>{loading?'…':lang==='it'?'Invia':'Ask'}</button></form>{answer&&<article className="answer">{answer}</article>}</section>}
