import React, { useEffect, useRef, useState } from 'react';
import { BlockMath, InlineMath } from 'react-katex';
import SimplexCanvas from './SimplexCanvas';
import { KNOWLEDGE_BASE_DIRECTORY, MENU_SECTOR_LIST, TUTORIAL_SLIDER_CONFIG } from './matrixData';
import { initCascadeScrollEngine } from './Scrollytelling';

const PROFILES=['Young Learner','Physicist','Mathematician'];
const VIEWS=['Clifford','Prime','Simplex','Cube'];
const labels={en:{tour:'The shared four-step tour',results:'Three result branches',matrix:'Language · audience · representation',note:'Educational visual toy model — not an established peer-reviewed physical theory.',lede:'The same visual journey adapts its language and explanatory depth for every audience. Use the controls below; every tour card and each result branch updates together.',open:'Open branch',step:'Step'},it:{tour:'Il tour condiviso in quattro passi',results:'Tre rami di risultati',matrix:'Lingua · pubblico · rappresentazione',note:'Modello visivo educativo — non una teoria fisica consolidata e sottoposta a peer review.',lede:'Lo stesso viaggio visivo adatta lingua e profondità esplicativa per ogni pubblico. Usa i controlli: ogni scheda del tour e ciascun ramo di risultati si aggiorna insieme.',open:'Apri il ramo',step:'Passo'}};
export default function App(){
 const [lang,setLang]=useState('en'),[profile,setProfile]=useState('Young Learner'),[view,setView]=useState('Clifford'),[step,setStep]=useState(0),[sector,setSector]=useState('Sector_EM_Maxwell');
 const tourRef = useRef(null); const resultRef = useRef(null);
 useEffect(() => initCascadeScrollEngine(setStep, tourRef.current), []);
 const t=labels[lang], record=KNOWLEDGE_BASE_DIRECTORY[`${sector}_${lang}_${profile}`], slides=TUTORIAL_SLIDER_CONFIG[lang][profile], selected=MENU_SECTOR_LIST.find(x=>x.id===sector);
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span>01</span> EIGHT SWITCHES</a></header>
  <section className="hero" id="top"><p className="eyebrow">Interactive research atlas · 2 × 3 × 4 presentation matrix</p><h1>{t.tour}</h1><p className="lede">{t.lede}</p><p className="disclosure">{t.note}</p></section>
  <ControlBar lang={lang} setLang={setLang} profile={profile} setProfile={setProfile} view={view} setView={setView}/>
  <section className="tour" ref={tourRef}><div className="tour-copy"><p className="eyebrow">{t.step.toUpperCase()} {step+1} / 4 · {profile.toUpperCase()}</p><h2>{slides[step].title}</h2><p>{slides[step].desc}</p><p className="cue">{view} lens: {telemetry(record,view)}</p><div className="steps">{slides.map((x,i)=><button onClick={()=>setStep(i)} className={i===step?'active':''} key={x.step}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="diagram"><SimplexCanvas step={step} activeView={view} sector={sector}/><span>{t.matrix}: {lang.toUpperCase()} · {profile} · {view}</span></div></section>
  <section className="branch-heading"><p className="eyebrow">{t.results.toUpperCase()}</p><h2>One directory, eighteen audience-language narratives, four representational lenses.</h2></section>
  <section className="branches">{MENU_SECTOR_LIST.map(item=>{const data=KNOWLEDGE_BASE_DIRECTORY[`${item.id}_${lang}_${profile}`];return <article className={`branch ${item.id===sector?'selected':''}`} key={item.id}><div><p className="eyebrow">{item.category}</p><h3>{data.title}</h3><p>{data.desc}</p></div><button onClick={()=>{setSector(item.id); if (window.matchMedia('(max-width: 800px)').matches) requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}}>{item.id===sector?'Active branch':t.open}</button></article>})}</section>
  <section className="result" ref={resultRef} tabIndex="-1"><article className="paper"><p className="eyebrow">{selected.category.toUpperCase()} · {view.toUpperCase()} VIEW</p><h2>{record.title}</h2><p>{record.desc}</p><ResultFormal sector={sector} profile={profile} lang={lang}/></article><aside className="proof-map"><p className="eyebrow">BRANCH VISUALIZATION</p><SimplexCanvas step={3} activeView={view} sector={sector}/><div className="view-pills">{VIEWS.map(v=><button onClick={()=>setView(v)} className={v===view?'active':''} key={v}>{v}: {telemetry(record,v)}</button>)}</div></aside></section>
  <ChatPanel lang={lang} profile={profile}/><footer><span>Clifford · Prime · Simplex · Cube</span><span>{t.note}</span></footer>
 </main>
}
function ControlBar({lang,setLang,profile,setProfile,view,setView}){return <section className="controls" aria-label="Presentation controls"><div className="control-title"><span>Presentation matrix</span><small>{lang.toUpperCase()} · {profile} · {view}</small></div><div className="control-group language-group"><p>LANGUAGE</p><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button><button className={lang==='it'?'active':''} onClick={()=>setLang('it')}>IT</button></div><div className="control-group audience-group"><p>AUDIENCE</p>{PROFILES.map(x=><button className={profile===x?'active':''} onClick={()=>setProfile(x)} key={x}>{x==='Young Learner'?'Learner':x==='Physicist'?'Physics':'Math'}</button>)}</div><div className="control-group lens-group"><p>LENS</p>{VIEWS.map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x}</button>)}</div></section>}
function telemetry(record,view){return view==='Clifford'?record.grade:view==='Prime'?`Multiplicity [${record.coordinate}]`:view==='Simplex'?record.simplex:record.cube}
function ResultFormal({ sector, profile, lang }) {
 if (profile === 'Young Learner') return null;
 const copy = {
  maxwell: { title: lang==='it'?'Teorema I: Il Campo di Maxwell':'Theorem I: The Maxwell Field Representation', intro: lang==='it'?'Le equazioni classiche collassano in un unico enunciato privo di coordinate. Il bivettore traccia le modifiche di fase nei canali elettromagnetici primi.':"Maxwell's classical field equations collapse into a single coordinate-free statement. The unified field bivector tracks phase modifications across prime channels.", label: lang==='it'?'Dimostrazione Analitica:':'Analytical Proof Sketch:', equation:String.raw`\nabla F = J \quad \text{where} \quad F = \mathbf{E} + I\mathbf{B}`, proof:String.raw`\nabla F = (\partial_t + \nabla) \cdot (\mathbf{E} + I\mathbf{B}) = J \implies \nabla \cdot \mathbf{E} = \rho, \quad \nabla \times \mathbf{B} - \partial_t \mathbf{E} = \mathbf{J}` },
  electroweak: { title: lang==='it'?'Teorema II: Rapporto di Impacchettamento':'Theorem II: The Electroweak Packing Fraction', intro: lang==='it'?'L’angolo di miscelazione debole emerge come frazione di spazio combinatoria dei nodi spaziali attivi rispetto al totale disponibile.':'Within this portal’s toy-model convention, the mixing angle is represented as a combinatorial packing fraction of active left-handed base vectors in the neutral-current space.', label: lang==='it'?'Vincolo del Sottospazio Spazio-Temporale:':'Topological Subspace Constraints:', equation:String.raw`\sin^2\theta_W \equiv \frac{|\mathcal{N}_L|}{|\mathcal{N}|} = \frac{4}{17} \approx 0.23529`, proof:String.raw`\mathcal{N}_L = \{ e_{ij} \in \mathcal{N} \mid \Pi_{BF}(e_{ij}) = 0 \land \chi_{LR}(e_{ij}) = L \} \implies |\mathcal{N}_L| = 4` },
  vacuum: { title: lang==='it'?'Teorema III: Inversione Scalare del Vuoto':'Theorem III: Identity Scalar Inversion', intro: lang==='it'?'Il neutrino sterile e il campo di Higgs sono manifestazioni duali dello stesso nucleo identità associato al vertice origine.':'The Sterile Neutrino state and the active Higgs-field operator are isomorphic configurations of the same multiplicative identity scalar core.', label: lang==='it'?'Mappatura Booleana NOT Antipodale:':'Boolean NOT Involution Mapping:', equation:String.raw`\mathcal{M}\left( \mathbf{\Phi}_H \cdot \mathbf{1} \right) \equiv \psi_\nu \iff \Lambda_{\text{Master}} = [+, 0, R, G_0]`, proof:String.raw`x \in \text{Cl}(4,4,0)_0 \implies x \mapsto \operatorname{NOT}(x) \equiv \Gamma_{192} \, x \, \widetilde{\Gamma}_{192}` }
  , strong: { title: lang==='it'?'Teorema IV: Confinamento del Colore':'Theorem IV: Color Confinement & Prime Coprimality', intro: lang==='it'?"La stabilità dei barioni è determinata dall'indivisibilità del fattore primo 7, che risulta algebricamente ortogonale alle interazioni deboli ed elettromagnetiche.":'Within this portal’s toy-model convention, baryon stability is represented by the coprimality of the prime 7 loop with lower-order gauge channels.', label: lang==='it'?'Invarianza del Ciclo del Piano di Fano:':'Fano Plane Topological Trap:', equation:String.raw`\gcd(3^\alpha \cdot 5^\beta, 7) = 1 \quad \forall \alpha, \beta \in \mathbb{Z}^+`, proof:String.raw`\left[ \mathcal{D}_\mu^{(3,5)}, \mathcal{I}_7 \right] \cap \mathcal{I}_0 = \emptyset \implies \Psi_{\text{Baryon}} \not\to \text{Lepton States}` }
  , gravity: { title: lang==='it'?'Teorema V: Deformazione del Frame Field':'Theorem V: Gauge Theory Gravity & Localized Strain', intro: lang==='it'?'La densità di energia-impulso si esprime tramite lo sforzo elastico locale del reticolo, provocando la compressione degli assi spaziali a favore della dilatazione temporale.':'Within this portal’s educational toy model, energy-momentum densities are formalized as position-dependent distortions on the 8-cube frame field rather than an established replacement for Riemann curvature.', label: lang==='it'?'Tensore dello Sforzo Energetico di Noether:':'Canonical Noether Stress-Energy Contraction:', equation:String.raw`\mathbf{S}_{AB}(x) = h_A^\mu(x) h_B^\nu(x) \eta_{\mu\nu} - \eta_{AB}`, proof:String.raw`T^{\mu\nu} = \left\langle \gamma^\mu \left( \bar{\Psi} \gamma^\nu \mathcal{D}_\mu \Psi \right) \right\rangle_1 \implies \Delta V_{\text{cell}} \propto \text{Tr}(\mathbf{S}_{AB})` }
  , baryon: { title: lang==='it'?'Teorema VI: Conservazione del Numero Barionico':'Theorem VI: Baryon Conservation Loops', intro: lang==='it'?'La stabilità del protone emerge come vincolo topologico sul piano di Fano, dove il ciclo a 7 primi rimane invariato.':'Within this portal’s toy-model convention, proton stability is represented as a topological winding restriction over an embedded Fano plane.', label: lang==='it'?'Vincolo di Avvolgimento:':'Winding Constraint:', equation:String.raw`\nu_B \equiv \frac{\nu_7 \pmod 3}{3} \implies \left[ \mathcal{D}_\mu^{(3,5)}, \mathcal{I}_7 \right] \cap \mathcal{I}_0 = \emptyset`, proof:String.raw`\partial(\Delta_2)=0 \quad \text{in the portal’s combinatorial mapping}` }
  , gut: { title: lang==='it'?'Teorema VII: Giunzione di Grande Unificazione 210':'Theorem VII: Grand Unification Primorial Checkpoint', intro: lang==='it'?'La convergenza delle quattro forze fondamentali si manifesta al checkpoint primorale saturando lo spazio dei vettori d’azione.':'Within this portal’s toy-model convention, gauge tracks intersect at the primorial product 210 as projections of a Grade-4 quadrivector.', label: lang==='it'?'Frazione di Impacchettamento dei Tesseratti:':'Tesseract Combinatorial Sub-blocks:', equation:String.raw`\mathbf{\Omega}_{\text{GUT}} = e_1 \wedge e_2 \wedge f_1 \wedge e_3 \implies \mathbf{\Omega}_{\text{GUT}}^2 = -1`, proof:String.raw`\text{Faces}_{\text{Simplex}} = 70 \quad \longleftrightarrow \quad \text{Sub-blocks}_{\text{Octeract}} = 1120` }
  , chiral: { title: lang==='it'?'Teorema VIII: Violazione di Parità Massima':'Theorem VIII: Maximal Parity Violation', intro: lang==='it'?'La separazione asimmetrica sorge perché gli operatori deboli ad azione sinistra anti-commutano con gli stati a parità dispari.':'Within this portal’s toy-model convention, the asymmetric separation is represented by left-action weak derivative operators acting on odd-parity state vectors.', label: lang==='it'?'Vincolo di Chiralità:':'Chirality Constraint:', equation:String.raw`\{ \mathcal{D}_\mu^{(5)}, \Psi_L \} \neq 0 \quad \land \quad [ \mathcal{D}_\mu^{(5)}, \Psi_R ] = 0`, proof:String.raw`\Psi_L \in \mathcal{I}_L, \quad \Psi_R \in \mathcal{I}_R` }
  , horizon: { title: lang==='it'?'Teorema IX: Chiusura della Periodicità di Bott':'Theorem IX: Global Boundary & Bott Periodicity', intro: lang==='it'?"La saturazione dell'elemento pseudoscalare massimo al vertice (11111111) impone un reset involutivo globale del volume.":'Within this portal’s toy-model convention, saturation of the maximal pseudoscalar volume at vertex node (11111111) represents a global boundary-reset condition.', label: lang==='it'?"Limite Cosmico dell'Orizzonte di Hubble:":'Macroscopic Hubble Boundary Reset:', equation:String.raw`I_8 = \gamma_1\gamma_2\gamma_3\gamma_4\gamma_5\gamma_6\gamma_7\gamma_8 \implies I_8^2 = -1`, proof:String.raw`\Lambda_{\text{Master}} = [1,1,1,1] \otimes [1,1,1,1] \implies \text{Hamming Distance } D_H = 8` }
 };
 const result = sector==='Sector_EM_Maxwell' ? copy.maxwell : sector==='Sector_Electroweak_Unified' ? copy.electroweak : sector==='Sector_Color_Strong' ? copy.strong : sector==='Sector_Gravity_Strain' ? copy.gravity : sector==='Sector_Baryon_Conservation' ? copy.baryon : sector==='Sector_GUT_Junction' ? copy.gut : sector==='Sector_Chiral_Parity' ? copy.chiral : sector==='Sector_Cosmic_Horizon' ? copy.horizon : copy.vacuum;
 return <div className="theorem"><b>{result.title}</b><p>{result.intro}</p><BlockMath math={result.equation}/><div className="lemma"><b>{result.label}</b><BlockMath math={result.proof}/></div></div>;
}

function ChatPanel({lang,profile}){const [input,setInput]=useState('');const [answer,setAnswer]=useState('');const [loading,setLoading]=useState(false);async function ask(e){e.preventDefault();if(!input.trim()||loading)return;setLoading(true);setAnswer('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({spokenLang:lang,userProfile:profile,messages:[{role:'user',content:input}]})});if(!r.ok)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let text='',buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=done?'':lines.pop();for(const line of lines){if(!line.startsWith('data: ')||line.includes('[DONE]'))continue;try{text+=JSON.parse(line.slice(6)).choices?.[0]?.delta?.content||'';setAnswer(text)}catch{}}if(done)break}}catch{setAnswer(lang==='it'?'Il servizio chat non è disponibile.':'Chat is unavailable.')}finally{setLoading(false)}}return <section className="chat"><p className="eyebrow">CASCADE GUIDE · {profile.toUpperCase()}</p><h2>{lang==='it'?'Chiedi al modello':'Ask the model'}</h2><form onSubmit={ask}><input value={input} onChange={e=>setInput(e.target.value)} placeholder={lang==='it'?'Fai una domanda':'Ask a question'} maxLength="1000"/><button disabled={loading}>{loading?'…':lang==='it'?'Invia':'Ask'}</button></form>{answer&&<article className="answer">{answer}</article>}</section>}
