import React, { useState } from 'react';
import { BlockMath, InlineMath } from 'react-katex';
import SimplexCanvas from './SimplexCanvas';
import { KNOWLEDGE_BASE_DIRECTORY, MENU_SECTOR_LIST, TUTORIAL_SLIDER_CONFIG } from './matrixData';

const PROFILES=['Young Learner','Physicist','Mathematician'];
const VIEWS=['Clifford','Prime','Simplex','Cube'];
const labels={en:{tour:'The shared four-step tour',results:'Three result branches',matrix:'Language · audience · representation',note:'Educational visual toy model — not an established peer-reviewed physical theory.',lede:'The same visual journey adapts its language and explanatory depth for every audience. Use the controls below; every tour card and each result branch updates together.',open:'Open branch',step:'Step'},it:{tour:'Il tour condiviso in quattro passi',results:'Tre rami di risultati',matrix:'Lingua · pubblico · rappresentazione',note:'Modello visivo educativo — non una teoria fisica consolidata e sottoposta a peer review.',lede:'Lo stesso viaggio visivo adatta lingua e profondità esplicativa per ogni pubblico. Usa i controlli: ogni scheda del tour e ciascun ramo di risultati si aggiorna insieme.',open:'Apri il ramo',step:'Passo'}};
export default function App(){
 const [lang,setLang]=useState('en'),[profile,setProfile]=useState('Young Learner'),[view,setView]=useState('Clifford'),[step,setStep]=useState(0),[sector,setSector]=useState('Sector_EM_Maxwell');
 const t=labels[lang], record=KNOWLEDGE_BASE_DIRECTORY[`${sector}_${lang}_${profile}`], slides=TUTORIAL_SLIDER_CONFIG[lang][profile], selected=MENU_SECTOR_LIST.find(x=>x.id===sector);
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span>01</span> EIGHT SWITCHES</a><div className="lang"><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>English</button><button className={lang==='it'?'active':''} onClick={()=>setLang('it')}>Italiano</button></div></header>
  <section className="hero" id="top"><p className="eyebrow">Interactive research atlas · 2 × 3 × 4 presentation matrix</p><h1>{t.tour}</h1><p className="lede">{t.lede}</p><p className="disclosure">{t.note}</p></section>
  <ControlBar profile={profile} setProfile={setProfile} view={view} setView={setView} lang={lang}/>
  <section className="tour"><div className="tour-copy"><p className="eyebrow">{t.step.toUpperCase()} {step+1} / 4 · {profile.toUpperCase()}</p><h2>{slides[step].title}</h2><p>{slides[step].desc}</p><p className="cue">{view} lens: {telemetry(record,view)}</p><div className="steps">{slides.map((x,i)=><button onClick={()=>setStep(i)} className={i===step?'active':''} key={x.step}>{String(i+1).padStart(2,'0')}</button>)}</div></div><div className="diagram"><SimplexCanvas step={step} activeView={view} sector={sector}/><span>{t.matrix}: {lang.toUpperCase()} · {profile} · {view}</span></div></section>
  <section className="branch-heading"><p className="eyebrow">{t.results.toUpperCase()}</p><h2>One directory, eighteen audience-language narratives, four representational lenses.</h2></section>
  <section className="branches">{MENU_SECTOR_LIST.map(item=>{const data=KNOWLEDGE_BASE_DIRECTORY[`${item.id}_${lang}_${profile}`];return <article className={`branch ${item.id===sector?'selected':''}`} key={item.id}><div><p className="eyebrow">{item.category}</p><h3>{data.title}</h3><p>{data.desc}</p></div><button onClick={()=>setSector(item.id)}>{item.id===sector?'Active branch':t.open}</button></article>})}</section>
  <section className="result"><article className="paper"><p className="eyebrow">{selected.category.toUpperCase()} · {view.toUpperCase()} VIEW</p><h2>{record.title}</h2><p>{record.desc}</p><ResultFormal sector={sector} profile={profile} lang={lang}/></article><aside className="proof-map"><p className="eyebrow">BRANCH VISUALIZATION</p><SimplexCanvas step={3} activeView={view} sector={sector}/><div className="view-pills">{VIEWS.map(v=><button onClick={()=>setView(v)} className={v===view?'active':''} key={v}>{v}: {telemetry(record,v)}</button>)}</div></aside></section>
  <ChatPanel lang={lang} profile={profile}/><footer><span>Clifford · Prime · Simplex · Cube</span><span>{t.note}</span></footer>
 </main>
}
function ControlBar({profile,setProfile,view,setView,lang}){return <section className="controls"><div><p className="eyebrow">AUDIENCE</p>{PROFILES.map(x=><button className={profile===x?'active':''} onClick={()=>setProfile(x)} key={x}>{lang==='it'&&x==='Young Learner'?'Giovane Studente':lang==='it'&&x==='Physicist'?'Fisico':lang==='it'&&x==='Mathematician'?'Matematico':x}</button>)}</div><div><p className="eyebrow">REPRESENTATION</p>{VIEWS.map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x} view</button>)}</div></section>}
function telemetry(record,view){return view==='Clifford'?record.grade:view==='Prime'?`Multiplicity [${record.coordinate}]`:view==='Simplex'?record.simplex:record.cube}
function ResultFormal({sector,profile,lang}){const note=lang==='it'?'convenzione del portale, non una previsione del Modello Standard.':'a portal convention, not a Standard Model prediction.';if(sector==='Sector_Electroweak_Unified')return <div className="theorem"><b>{profile==='Mathematician'?'Proposition.':'Illustrative packing statement.'}</b><p>The selected neutral-channel diagram encodes <InlineMath math="4/17\approx0.2353"/> as {note}</p><BlockMath math="N_{\mathrm{selected}}=4,\quad N_{\mathrm{reference}}=17"/></div>;if(sector==='Sector_EM_Maxwell')return <div className="theorem"><b>Diagram note.</b><p>The active visualization presents the portal’s electromagnetic correspondence across the selected representation.</p><BlockMath math="\nabla F = J"/></div>;return <div className="theorem"><b>Diagram note.</b><p>The visual traces the portal’s identity-scalar and complement mapping as an educational convention.</p><BlockMath math="x\mapsto \operatorname{NOT}(x)"/></div>}

function ChatPanel({lang,profile}){const [input,setInput]=useState('');const [answer,setAnswer]=useState('');const [loading,setLoading]=useState(false);async function ask(e){e.preventDefault();if(!input.trim()||loading)return;setLoading(true);setAnswer('');try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({spokenLang:lang,userProfile:profile,messages:[{role:'user',content:input}]})});if(!r.ok)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let text='',buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=done?'':lines.pop();for(const line of lines){if(!line.startsWith('data: ')||line.includes('[DONE]'))continue;try{text+=JSON.parse(line.slice(6)).choices?.[0]?.delta?.content||'';setAnswer(text)}catch{}}if(done)break}}catch{setAnswer(lang==='it'?'Il servizio chat non è disponibile.':'Chat is unavailable.')}finally{setLoading(false)}}return <section className="chat"><p className="eyebrow">CASCADE GUIDE · {profile.toUpperCase()}</p><h2>{lang==='it'?'Chiedi al modello':'Ask the model'}</h2><form onSubmit={ask}><input value={input} onChange={e=>setInput(e.target.value)} placeholder={lang==='it'?'Fai una domanda':'Ask a question'} maxLength="1000"/><button disabled={loading}>{loading?'…':lang==='it'?'Invia':'Ask'}</button></form>{answer&&<article className="answer">{answer}</article>}</section>}
