import React,{useEffect,useRef}from 'react';
import * as THREE from 'three';
const tones={learner:{Spatial:0x69dff0,Temporal:0xff9d78},physics:{Spatial:0x66baff,Temporal:0xff6f91},math:{Spatial:0xa38cff,Temporal:0xffcb6b}};
const addLine=(root,a,b,color,opacity=.75)=>root.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color,transparent:true,opacity})));
export default function GenesisCanvas({stage,metricMode,profile}){const ref=useRef(null);useEffect(()=>{const host=ref.current;if(!host)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,host.clientWidth/440,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,440);host.appendChild(renderer.domElement);const root=new THREE.Group();scene.add(root);const audience=profile==='Young Learner'?'learner':profile==='Physicist'?'physics':'math',temporal=metricMode==='Temporal',accent=tones[audience][metricMode],quiet=new THREE.MeshBasicMaterial({color:0x35405e,transparent:true,opacity:.55}),active=new THREE.MeshBasicMaterial({color:accent}),points=Array.from({length:8},(_,i)=>{const a=i*Math.PI/4-Math.PI/2,r=stage<2?1:stage<5?2.15:2.85;return new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r*(temporal?1.18:1),0)});
if(stage===0){
if(audience==='learner'){const floor=new THREE.Mesh(new THREE.PlaneGeometry(5.8,3.8,7,5),new THREE.MeshBasicMaterial({color:accent,wireframe:true,transparent:true,opacity:.16}));floor.position.z=-.3;root.add(floor);for(let i=0;i<26;i++){const dust=new THREE.Mesh(new THREE.SphereGeometry(.025,8,8),new THREE.MeshBasicMaterial({color:0xa78bfa,transparent:true,opacity:.7}));dust.position.set((Math.random()-.5)*5.4,(Math.random()-.5)*3.3,-.1);root.add(dust)}root.add(new THREE.Mesh(new THREE.CircleGeometry(.42,32),quiet))}
else if(audience==='physics'){[.42,.9,1.45].forEach((radius,index)=>{const ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.018,8,48),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.7-index*.15}));ring.rotation.x=Math.PI/2;root.add(ring)});addLine(root,new THREE.Vector3(-2.5,0,0),new THREE.Vector3(2.5,0,0),accent,.35);addLine(root,new THREE.Vector3(0,-1.7,0),new THREE.Vector3(0,1.7,0),accent,.35)}
else{for(let x=-2;x<=2;x++)for(let y=-2;y<=2;y++){const isIdentity=x===y;const cell=new THREE.Mesh(new THREE.BoxGeometry(.28,.28,.045),new THREE.MeshBasicMaterial({color:isIdentity?accent:0x24304a,transparent:true,opacity:isIdentity?.9:.55}));cell.position.set(x*.38,y*.38,0);root.add(cell)}root.add(new THREE.Mesh(new THREE.BoxGeometry(.14,.14,.14),active))}
}else{const nodeGeometry=audience==='math'?new THREE.BoxGeometry(.22,.22,.22):new THREE.SphereGeometry(audience==='learner'?.19:.13,20,20);points.forEach((p,i)=>{const n=new THREE.Mesh(nodeGeometry,i<stage?active:quiet);n.position.copy(p);n.rotation.z=i*Math.PI/8;root.add(n)});for(let i=1;i<stage;i++)addLine(root,points[i-1],points[i],accent,.9);if(stage>=2)for(let i=0;i+1<stage;i+=2)addLine(root,points[i],points[i+1],accent,1);
if(audience==='learner'){if(stage>=2){const floor=new THREE.Mesh(new THREE.PlaneGeometry(5.5,3.8,5,5),new THREE.MeshBasicMaterial({color:accent,wireframe:true,transparent:true,opacity:.25}));floor.position.z=-.55;root.add(floor)}if(stage>=3){const gear=new THREE.Mesh(new THREE.TorusGeometry(.72+stage*.04,.07,10,24),active);gear.rotation.x=Math.PI/2;root.add(gear)}if(stage>=5)root.add(new THREE.Mesh(new THREE.RingGeometry(1.35,1.39,32),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.75})))}
if(audience==='physics'){if(stage>=2){const cone=new THREE.Mesh(new THREE.ConeGeometry(.9+stage*.08,2.2,32,1,true),new THREE.MeshBasicMaterial({color:accent,wireframe:true,transparent:true,opacity:.35}));cone.rotation.x=Math.PI/2;cone.scale.y=temporal?1.35:1;root.add(cone)}if(stage>=4){const grid=new THREE.GridHelper(5.6,8,accent,0x263552);grid.rotation.x=Math.PI/2;grid.position.z=-.6;root.add(grid)}}
if(audience==='math'){if(stage>=2){for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++){const cell=new THREE.Mesh(new THREE.BoxGeometry(.24,.24,.04),new THREE.MeshBasicMaterial({color:(x+y+stage)%2?accent:0x273252,transparent:true,opacity:.65}));cell.position.set(x*.34,y*.34,-.25);root.add(cell)}}}
if(stage>=6){const orbit=new THREE.Mesh(new THREE.TorusGeometry(1.1,.035,10,48),active);orbit.rotation.x=Math.PI/2;orbit.scale.y=temporal?1.3:1;root.add(orbit)}if(stage===8){points.forEach((p,i)=>points.slice(i+1).forEach(q=>addLine(root,p,q,accent,.15)));const boundary=new THREE.Mesh(new THREE.TorusGeometry(3.15,.025,8,64),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.85}));boundary.rotation.x=Math.PI/2;root.add(boundary)}}
camera.position.set(0,stage>=6?1.2:0,8.5);const target=new THREE.Vector3();let frame;const draw=()=>{root.rotation.z+=audience==='learner'?.002:.0012;camera.lookAt(target);renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();const resize=()=>{camera.aspect=host.clientWidth/440;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,440)};addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);renderer.dispose();host.replaceChildren()}},[stage,metricMode,profile]);return <div className="canvas genesis-canvas" ref={ref} aria-label={`Genesis stage ${stage} visual story`}/>}
