// Master 2D Clifford lattice matrix directory (B+F vs B-F).
const nodes = [
 ['Sector_Vacuum_Origin','Foundational Symmetries','Grade 0 Pure Scalar','B+F=0, B-F=0','Empty Set Vertex Core (Ø)','[0, 0, 0, 0] ⊗ [0, 0, 0, 0]','The Cl(0,0) Trivial Vacuum Origin Root',"La Radice dell'Origine del Vuoto Banale Cl(0,0)",'Located at the absolute grid origin, this scalar multiplier root carries zero active base or fiber dimensions and acts as the baseline reference field.','Situata all’origine assoluta della griglia, questa radice scalare non ha dimensioni attive di base o fibra e agisce come campo di riferimento.'],
 ['Sector_Inject_Base_Real','Foundational Symmetries','Grade 1 Vector','B+F=1, B-F=+1','0-face Vertex','[+, 0, L, G₀] ⊗ [0, 0, 0, 0]','The Cl(1,0) Macroscopic Base Injector','Iniettore di Base Reale Cl(1,0)','This primary cell injects a real space-like vector onto the base manifold, generating the background coordinates for physical spatial paths.','Questa cella primaria inietta un vettore reale di tipo spazio sulla varietà di base, generando le coordinate di sfondo per i percorsi fisici.'],
 ['Sector_Inject_Fiber_Clock','Foundational Symmetries','Grade 1 Pseudo-Vector','B+F=1, B-F=-1','Internal Face Edge','[0, 1, L, G₀] ⊗ [1, 0, 0, ν]','The Cl(0,1) Internal Complex Fiber Injector','Iniettore della Fibra Complessa Cl(0,1)','This cell injects a complex phase coordinate inside the gauge fiber, functioning as the phase clock for the portal’s electromagnetic mapping.','Questa cella inietta una coordinata di fase complessa nella fibra di gauge, fungendo da orologio di fase per la mappatura elettromagnetica del portale.'],
 ['Sector_EM_Maxwell','Foundational Symmetries','Grade 2 Bivector','B+F=8, B-F=+6','1-face (Edge Segment)','[+, 1, L, G₀] ⊗ [1, 0, 0, ν]','The Maxwell Field Tensor: ∇F = J','Tensore del Campo di Maxwell: ∇F = J','Formed by the tensor composition of the Cl(1,0) and Cl(0,1) building blocks, compiling the portal’s electromagnetic channels into a coordinate-free Clifford statement.','Formulato dal prodotto tensoriale dei blocchi Cl(1,0) e Cl(0,1), compilando i canali elettromagnetici del portale in un enunciato Clifford.'],
 ['Sector_Gravity_Strain','Foundational Symmetries','Grade 6 Hexvector Connection','B+F=8, B-F=+4','5-face (Boundary Flank)','[±, 0/1, L/R, G₀/₁] ⊗ [Lattice Strain Field]','Gauge Theory Gravity & Elastic Strain Connection','Gravità della Teoria di Gauge e Sforzo Elastico','Gravity replaces Riemann metric tensors with a localized translation gradient that skews 8-cube lattice axes under local mass-energy density.','La gravità sostituisce i tensori metrici di Riemann con un gradiente di traslazione localizzato che inclina gli assi del reticolo a 8 cubi.'],
 ['Sector_Quaternionic_Base','Structural Realignments','Grade 2 Bivector Operator','B+F=2, B-F=+2','2-face (Triangle Surface Canvas)','[+, 1, L, G₀] ⊗ [0, 0, 0, 0]','The Cl(2,0) Macroscopic Quaternionic Base Cell','La Cella di Base Quaternionica Cl(2,0)','This cell maps two space-like vector choices onto the manifold, regenerating Hamilton’s real quaternionic spin algebra and its rotational constraints.','Questa cella mappa due scelte vettoriali di tipo spazio sulla varietà, rigenerando l’algebra quaternionica reale di Hamilton e i suoi vincoli rotazionali.'],
 ['Sector_Quaternionic_Fiber','Structural Realignments','Grade 2 Fiber Rotor','B+F=2, B-F=-2','2-face (Hidden Gauge Cluster)','[0, 1, L, G₀] ⊗ [0, 1, 0, ν]','The Cl(0,2) Electroweak Gauge Fiber Ring',"L'Anello della Fibra di Gauge Elettrodebole Cl(0,2)",'This cell locks two negative-squaring vectors inside the quantum fiber, creating the portal’s split-quaternionic phase space for SU(2) mappings.','Questa cella blocca due vettori a quadratura negativa nella fibra quantistica, creando lo spazio di fase quaternionico per le mappature SU(2).'],
 ['Sector_Baryon_Conservation','Structural Realignments','Grade 3 Trivector Loop','B+F=8, B-F=+2','2-face Triangular Boundary','[±, 0, L, G₀] ⊗ [0, 0, 1, ν]','Topological Baryon Stability & 7-Prime Core','Stabilità Barionica Topologica e Core a 7-Primi','Baryon number conservation is a rigid topological winding across cyclic loops of an embedded Fano plane in this toy model.','La conservazione del numero barionico è un avvolgimento topologico rigido attraverso i cicli di un piano di Fano incorporato in questo modello giocattolo.'],
 ['Sector_Electroweak_Unified','Structural Realignments','Grade 2/4 Ideal Intersection','B+F=8, B-F=0','Unified Edge Connectivity Graph K₈','[-, 1, L, G₀↔G₁] ⊗ [1, 1, 0, ν]','The Saturated Electroweak Gauge Sector','Il Settore di Gauge Elettrodebole Saturato','The centered 4-base, 4-fiber mesh contains 17 neutral paths; its 4/17 fraction is an internal packing convention, not a Standard Model prediction.','La rete centrata di 4 basi e 4 fibre contiene 17 percorsi neutri; la sua frazione 4/17 è una convenzione interna di impacchettamento, non una previsione del Modello Standard.'],
 ['Sector_Vacuum_Mass_Generation','Speculative Frontiers','Grade 0 Identity / Grade 7 Inversion','B+F=0, B-F=0','The Empty Face (Ø) & 6-face Envelopes','[+, 0, R, G₀] ⊗ [0, 0, 0, 0]','The Higgs VEV, Sterile Neutrino & Charge Conjugation','Il VEV di Higgs, il Neutrino Sterile e la Coniugazione di Carica','The passive identity is mapped to a sterile-neutrino state; active matrix actions map it to the portal’s mass-generation convention.','L’identità passiva è mappata a uno stato di neutrino sterile; azioni matriciali attive la mappano alla convenzione di generazione della massa del portale.'],
 ['Sector_GUT_Junction','Speculative Frontiers','Grade 4 Quadrivector','B+F=8, B-F=-4','3-face (Internal Cell Cluster)','[-, 1, R, G₁] ⊗ [1, 1, 1, 1]','The Primorial Saturation Checkpoint','Il Checkpoint di Saturazione Primorale','Grand Unification is represented as an arithmetic saturation checkpoint at the primorial product 210, where gauge tracks overlap in one matrix block.','La Grande Unificazione è rappresentata come checkpoint di saturazione aritmetica al prodotto primorale 210, dove i canali di gauge si sovrappongono in un blocco di matrice.'],
 ['Sector_Cosmic_Horizon','Speculative Frontiers','Grade 8 Pseudoscalar Volume','B+F=8, B-F=-8','1 Whole 7-face Simplex','[1, 1, 1, 1] ⊗ [1, 1, 1, 1]','The Maximal Pseudoscalar Horizon Boundary',"L'Orizzonte Pseudoscalare Massimo di Confine",'The 256-multiplicity element maps to the global pseudoscalar volume and the anti-podal vertex in the portal’s boundary-reset convention.','L’elemento a molteplicità 256 si mappa sul volume pseudoscalare globale e sul vertice antipodale nella convenzione di reset del confine del portale.'],
];
export const KNOWLEDGE_BASE_DIRECTORY = {};
for (const [id,category,grade,coordinate,simplex,cube,enTitle,itTitle,enDesc,itDesc] of nodes) {
 const base={id,category,grade,coordinate,simplex,cube};
 for (const [lang,title,desc] of [['en',enTitle,enDesc],['it',itTitle,itDesc]]) {
  KNOWLEDGE_BASE_DIRECTORY[`${id}_${lang}_Physicist`]={...base,title,desc};
  KNOWLEDGE_BASE_DIRECTORY[`${id}_${lang}_Mathematician`]={...base,title,desc};
  KNOWLEDGE_BASE_DIRECTORY[`${id}_${lang}_Young Learner`]={...base,title,desc};
 }
}
export const MENU_SECTOR_LIST = nodes.map(([id,category])=>({id,category}));
const tour={en:{'Young Learner':['Eight quiet switches wait in a sandbox.','Choose space or time paths.','Choose the sandbox or a wheel.','Choose the final left or right path.'],Physicist:['Isotropic ground state.','Witt signature split.','Base-fiber grading.','Chiral orientation.'],Mathematician:['Isotropic radical root.','Quadratic-form split.','Grade filtration.','Minimal ideal involution.']},it:{'Young Learner':['Otto interruttori tranquilli attendono nel recinto.','Scegli percorsi di spazio o tempo.','Scegli il recinto o una ruota.','Scegli il percorso finale sinistro o destro.'],Physicist:['Stato fondamentale isotropo.','Scissione della segnatura di Witt.','Gradazione base-fibra.','Orientamento chirale.'],Mathematician:['Radice isotropa radicale.','Scissione della forma quadratica.','Filtrazione del grado.','Involuzione dell’ideale minimo.']}};
export const TUTORIAL_SLIDER_CONFIG=Object.fromEntries(Object.entries(tour).map(([lang,profiles])=>[lang,Object.fromEntries(Object.entries(profiles).map(([profile,items])=>[profile,items.map((desc,i)=>({step:i+1,title:`${lang==='it'?'Passo':'Step'} ${i+1}`,desc}))]))]));
