import K from './projectiveData.js';

// Copy for step 9 of the equations page: one more generator, and a null pair (English and Italian).
// Every number is read from selfcheck/projective.json (exact, standard library) and selfcheck/projective_matrix.json (numpy).
const CN = K.pj.counts;
export const NAMES = { en: { 'space,0': 'Euclid', 'space,-1': 'elliptic', 'space,1': 'hyperbolic', 'lorentz,0': 'Poincaré', 'lorentz,-1': 'de Sitter', 'lorentz,1': 'anti-de Sitter' },
  it: { 'space,0': 'euclideo', 'space,-1': 'ellittico', 'space,1': 'iperbolico', 'lorentz,0': 'Poincaré', 'lorentz,-1': 'de Sitter', 'lorentz,1': 'anti-de Sitter' } };
export const baseSq = (kind, n) => (kind === 'space' ? Array(n).fill(-1) : [1, ...Array(n - 1).fill(-1)]);
export const AXN = ['t', 'x', 'y', 'z', 'u', 'v', 'w'];
export const sgn = v => (v > 0 ? '+1' : v < 0 ? '−1' : '0');
const pe = (k, one, many) => (k === 1 ? one : many);
const C2 = n => n * (n - 1) / 2;
export const key = (kind, n, s) => `${kind},${n},${s}`;
// the inner product of two points P(x), P(y) on a line, in a space base: (1/2)|x - y|^2
export const pdot = (x, y) => (x - y) * (x - y) / 2;
const PTS = [0, 1, 2, 3];

const COPY = {
  en: {
    p1: {
      title: 'Flat, curved, conformal: one more bit, or two',
      lede: 'Step 7 added one generator of square s to the frame and got de Sitter or anti-de Sitter. Here that move is made on purpose and for all three squares: s = 0, −1, +1. Every choice gives the same number of generators, C(n+1,2), and the same rule [B_an, B_bn] = −2s B_ab. With a space base the three are the Euclidean, elliptic and hyperbolic geometries; with a Lorentz base they are Poincaré, de Sitter and anti-de Sitter. The case s = 0 is the degenerate algebra of plane-based projective geometric algebra (PGA). Adding two generators, one of square −1 and one of +1, gives a null pair ε and o. A point is the null vector P(x) = o + x − ½x²ε, a plane is the vector n + δε, a sphere is P(c) − ½r²ε, and the mirrors in planes and spheres generate the Euclidean and the conformal motions: conformal geometric algebra (CGA) contains PGA, as the algebra generated by the base and ε. This is standard material; the page checks it on the bit rule and reads the extra generators as extra bits of the cube. It does not touch force or dynamics (that is the next step), and it claims no physical role.',
      tableH: 'The counts', cols: ['n', 'generators C(n+1,2)', 'Euclid or Poincaré subalgebra', 'conformal C(n+2,2)', 'PGA dimension', 'CGA dimension', 'plane mirrors for any isometry'],
      pickH: 'Pick a base, a square and a dimension', pick: 'base · square s of the extra generator · n axes',
      kinds: { space: 'space base', lorentz: 'Lorentz base' }, sLabel: s => `s = ${sgn(s)}`,
      picH: 'The extra generator',
      picCap: (n, kind, s) => `${n} base axes${kind === 'lorentz' ? ' (the first is time)' : ''} and the extra generator in the middle. Each spoke is the plane B_an of an axis with the extra one; its square is −η_a s, shown on the spoke. ${s === 0 ? 'The extra generator is null: every spoke squares to 0 and the n planes commute.' : 'The planes do not commute: two of them give a plane of the base.'}`,
      info: (kind, n, s, r) => [
        `${NAMES.en[kind + ',' + s]} geometry: the bivectors of ${n + 1} axes, ${r.dimension} generators, signature (+${r.signature_plus_minus[0]}, −${r.signature_plus_minus[1]}) counting the squares +1 and −1.`,
        s === 0 ? `[B_an, B_bn] = 0: the n = ${n} translations commute with each other and form an ideal. The Killing form vanishes exactly on them (${r.killing.zero} directions).` : `[B_an, B_bn] = −2s B_ab = ${r.commutator_coefficient} B_ab. The Killing form has ${r.killing.positive} positive and ${r.killing.negative} negative directions, the product (${r.signature_plus_minus[0]})(${r.signature_plus_minus[1]}) = ${r.signature_plus_minus[0] * r.signature_plus_minus[1]} of the +1 and −1 axes.`,
        `Step 7: half the commutator constant is the coefficient of e∧e in the curvature, k = −s = ${r.curvature_coefficient}. As the extra planes are rescaled by λ the constants go to those of s = 0 like λ²: the flat case is the limit.`],
      nullH: 'The null pair', nullCap: 'The extra plane of the null pair: e_m of square +1 along the first axis, e_p of square −1 along the second. The two diagonals are ε = e_p + e_m and o = (e_m − e_p)/2, both null, with ε·o = 1. A point is a null vector P(x) = o + x − ½x²ε; for points on a line in a space base P(x)·P(y) = ½|x − y|².',
      ptsCols: ['x', 'P(x) = o + x + ½|x|² ε', ...PTS.map(v => `P(x)·P(${v})`)],
      motionsH: 'Moves as products of mirrors', motionsCols: ['move', 'versor', 'mirrors', 'checked'],
      motionsRows: [
        ['translation by t', '1 + ½ t ε', '2 parallel planes', 'translation'], ['rotation', 'a b (two vectors of the base)', '2 planes through a point', 'rotation'],
        ['dilation', '1 + u e_p e_m', '2 concentric spheres', 'dilation'], ['inversion in a sphere', 'P(c) − ½r²ε', '1 sphere', 'inversion'], ['reflection in a plane', 'n + δε', '1 plane', 'plane']],
      motionsNote: 'Each row is a sandwich on P(x), exact on random rational points. Two parallel planes multiply to a translation, two concentric spheres to a dilation, and every isometry of R^n is at most n + 1 plane mirrors: one brings the origin home, then Cartan–Dieudonné of step 8 finishes. The null vectors ε and o themselves are not mirrors: a·a = 0.',
      viewsH: n => `Every view at n = ${n}`,
      views: r => {
        const n = r.n_value, c = CN[n], tg = ['checked', 'standard'];
        const cl = { h: 'Clifford', t: `One more generator of square s gives ${c.ladder_generators} bivectors and [B_an, B_bn] = −2s B_ab; s = 0 is the degenerate algebra with ${c.pga_dimension} blades (PGA). A null pair gives ${c.cga_dimension} blades, and Cl(p+1,q+1) = Cl(p,q) ⊗ M₂(ℝ): four pairs give M₁₆(ℝ). Exact for n = 2 to 6 (null pair n = 2 to 4); numpy agrees.`, tags: tg };
        const cu = { h: 'Cube and demicube', t: `The extra generator is one more bit: the cube has ${1 << (n + 1)} corners and ${c.pga_dimension} blades of PGA are its corners. The null pair is two more bits: ${c.cga_dimension} corners. The planes needed to move a point are ${c.planes_to_move_a_point} = n + 1 at most, one more than the mirrors of step 8.`, tags: ['checked', 'ours'] };
        const si = { h: 'Simplex', t: `${n + 1} axes are the corners of a simplex with ${c.ladder_generators} edges: ${C2(n)} inside the base (rotations or boosts) and ${n} joining the extra axis. With the null pair there are ${n + 2} corners and ${c.conformal_generators} edges: ${C2(n)} ${pe(C2(n), 'rotation', 'rotations')}, ${n} translations, ${n} special conformal maps and the edge between ε and o, the dilation. They are regrouped, not renamed: a translation is e_i e_p + e_i e_m, a sum of two edges.`, tags: ['checked', 'ours'] };
        const la = { h: 'Labels', t: `T_i = e_i ε (translations), K_i = e_i o (special conformal), D = e_p e_m (dilation) and B_ij (rotations). The dilation scales T by +2 and K by −2 under the commutator, exactly, so [D, T] = 2T and [D, K] = −2K. Labels are notation.`, tags: ['checked', 'standard'] };
        const ma = { h: 'Maxwell', t: `Maxwell’s equations in four dimensions are conformally invariant: standard, not rebuilt here. What is checked is the group that would act: ${c.conformal_generators} generators in ${n} dimensions, containing the ${c.euclid_generators} of Euclid or Poincaré.`, tags: ['standard'] };
        const ym = { h: 'Yang–Mills (step 4)', t: `Classical Yang–Mills in four dimensions is conformally invariant: standard, not rebuilt here. The same ${c.conformal_generators} generators act on the base space, not on the internal index.`, tags: ['standard'] };
        const di = { h: 'Dirac', t: `The massless Dirac equation is conformally invariant, and the mass term breaks the dilation: standard, not rebuilt here. The Poincaré subalgebra with ${c.euclid_generators} generators is the one that survives with mass. Nothing is solved.`, tags: ['standard', 'open'] };
        return [cl, cu, si, la, ma, ym, di];
      },
      idH: 'What was checked, and where', idCols: ['n', 'ladder s = 0, ±1', 'null pair, points', 'translation, rotation, dilation, inversion, plane', 'PGA inside CGA', 'plane mirrors ≤ n + 1', 'conformal algebra'],
      idNote: 'Both bases. Ladder: closure, Jacobi, squares, commutators, the Killing form, the contraction (n = 2 to 6). Null pair and moves: n = 2 to 4. PGA inside CGA: an injective algebra homomorphism on all pairs of basis elements (n = 2, 3). Plane mirrors: n = 2, 3. Conformal algebra: C(n+2,2) generators, closure, Killing signature (n = 2 to 4). Exact rational arithmetic.',
      dblH: 'Two more generators, a factor M₂(ℝ)', dblCols: ['pairs k', 'algebra Cl(k,k)', 'matrix size', 'dimension'],
      dblNote: 'Explicit real matrices: each null pair doubles the size and the products of the generators stay a basis of all matrices, so Cl(k,k) is the full matrix algebra of size 2^k, up to M₁₆(ℝ) at k = 4 (the rank is computed modulo a prime, which can only underestimate it). That is the factor by which Cl(p+4,q+4) differs from Cl(p,q): the repeat of types every four pairs, not a wall.',
      xrH: 'What each view teaches the others',
      xr: [
        ['ours', 'Cube → extra bits. The same bit rule: one extra generator is one more bit with square 0, −1 or +1, and the null pair is two bits (−1, +1). Reading them as bits of the cube is ours; the geometries themselves are textbook.'],
        ['checked', 'Step 7 → step 9. The constant of the extra generator is the one of step 7: half of −2s is the coefficient k = −s of e∧e in the curvature. Poincaré, de Sitter and anti-de Sitter all have C(n+1,2) generators.'],
        ['checked', 'Step 8 → step 9. Planes and spheres are non-null vectors, so they are mirrors; the isometries of R^n are products of at most n + 1 of them. The null vectors ε and o are not mirrors, which is why the degenerate case needed its own page.'],
        ['standard', 'The three plane-based algebras (Euclid R^{d,0,1}, elliptic R^{d+1,0,0}, hyperbolic R^{d,1,0}) and the extension to spheres are as the paper of Dorst and De Keninck describes them, which we read. That the equations of motion are the same in the three is stated there and attributed to Gunn; we did not re-derive it. We have not compared with the other treatments.']
      ],
      matH: 'Independent check with matrices',
      mat: 'With Jordan–Wigner gamma matrices (numpy), for both bases and n = 2 to 4: ε and o are nilpotent with εo + oε = 2, P(x) is null and P(x)P(y) + P(y)P(x) = −(x−y)², and translation, rotation, dilation, inversion and plane reflection send P(x) to the expected point. The commutators [B_an, B_bn] = −2s B_ab hold for s = ±1 (n = 2 to 5) and vanish for s = 0, where the extra generator is the nilpotent matrix ε. The 2^(n+1) products of the base gammas and ε are independent matrices, so PGA is represented faithfully. The conformal algebra closes and its Killing form has (+1 axes)(−1 axes) positive eigenvalues. Wrong versions fail: the opposite sign in P(x), o replaced by −o, the translation coefficient 1 instead of ½, a pair of equal signs (ε is then not null), and a mirror in ε, whose matrix is singular.',
      open: [
        ['open', 'Dynamics. Force and forque, and the Newton–Euler equations, are the next step and are not here. That the equations of motion coincide in the three PGAs is cited, not re-derived; conformal dynamics is not developed in the source we read.'],
        ['open', 'Whether any of this has a physical role in the model. The extra generator is a geometry, not a field.'],
        ['open', 'Nothing here selects three generations.']
      ],
      dl: { h: 'Check it yourself', text: 'Two Python files. The first (standard library only, with mirrors_selfcheck.py beside it) rebuilds everything above, exactly. The second (needs numpy) compares with explicit matrices and runs wrong versions that must fail.', py: 'Download projective_selfcheck.py', py2: 'Download projective_matrix_check.py', json: 'Download projective.json', cmd: 'python3 projective_selfcheck.py --compare projective.json   ·   python3 projective_matrix_check.py --compare projective_matrix.json' }
    }
  },
  it: {
    p1: {
      title: 'Piatto, curvo, conforme: un bit in più, o due',
      lede: 'Il passo 7 aggiungeva alla tetrade un generatore di quadrato s e otteneva de Sitter o anti-de Sitter. Qui la mossa è fatta apposta e per tutti e tre i quadrati: s = 0, −1, +1. Ogni scelta dà lo stesso numero di generatori, C(n+1,2), e la stessa regola [B_an, B_bn] = −2s B_ab. Con una base spaziale i tre sono le geometrie euclidea, ellittica e iperbolica; con una base di Lorentz sono Poincaré, de Sitter e anti-de Sitter. Il caso s = 0 è l’algebra degenere dell’algebra geometrica proiettiva basata sui piani (PGA). Aggiungendo due generatori, uno di quadrato −1 e uno di +1, si ottiene una coppia nulla ε e o. Un punto è il vettore nullo P(x) = o + x − ½x²ε, un piano è il vettore n + δε, una sfera è P(c) − ½r²ε, e gli specchi in piani e sfere generano i moti euclidei e conformi: l’algebra geometrica conforme (CGA) contiene la PGA, come algebra generata dalla base e da ε. È materiale standard; la pagina lo verifica sulla regola dei bit e legge i generatori in più come bit in più del cubo. Non tocca forza e dinamica (è il passo successivo), e non afferma alcun ruolo fisico.',
      tableH: 'I conteggi', cols: ['n', 'generatori C(n+1,2)', 'sottoalgebra euclidea o di Poincaré', 'conforme C(n+2,2)', 'dimensione PGA', 'dimensione CGA', 'specchi-piano per ogni isometria'],
      pickH: 'Scegli una base, un quadrato e una dimensione', pick: 'base · quadrato s del generatore in più · n assi',
      kinds: { space: 'base spaziale', lorentz: 'base di Lorentz' }, sLabel: s => `s = ${sgn(s)}`,
      picH: 'Il generatore in più',
      picCap: (n, kind, s) => `${n} assi di base${kind === 'lorentz' ? ' (il primo è il tempo)' : ''} e il generatore in più al centro. Ogni raggio è il piano B_an di un asse con quello in più; il suo quadrato è −η_a s, scritto sul raggio. ${s === 0 ? 'Il generatore in più è nullo: ogni raggio ha quadrato 0 e gli n piani commutano.' : 'I piani non commutano: due di essi danno un piano della base.'}`,
      info: (kind, n, s, r) => [
        `Geometria ${NAMES.it[kind + ',' + s]}: i bivettori di ${n + 1} assi, ${r.dimension} generatori, segnatura (+${r.signature_plus_minus[0]}, −${r.signature_plus_minus[1]}) contando i quadrati +1 e −1.`,
        s === 0 ? `[B_an, B_bn] = 0: le n = ${n} traslazioni commutano tra loro e formano un ideale. La forma di Killing si annulla esattamente su di esse (${r.killing.zero} direzioni).` : `[B_an, B_bn] = −2s B_ab = ${r.commutator_coefficient} B_ab. La forma di Killing ha ${r.killing.positive} direzioni positive e ${r.killing.negative} negative, il prodotto (${r.signature_plus_minus[0]})(${r.signature_plus_minus[1]}) = ${r.signature_plus_minus[0] * r.signature_plus_minus[1]} degli assi +1 e −1.`,
        `Passo 7: metà della costante del commutatore è il coefficiente di e∧e nella curvatura, k = −s = ${r.curvature_coefficient}. Riscalando i piani in più di λ le costanti tendono a quelle di s = 0 come λ²: il caso piatto è il limite.`],
      nullH: 'La coppia nulla', nullCap: 'Il piano in più della coppia nulla: e_m di quadrato +1 lungo il primo asse, e_p di quadrato −1 lungo il secondo. Le due diagonali sono ε = e_p + e_m e o = (e_m − e_p)/2, entrambe nulle, con ε·o = 1. Un punto è un vettore nullo P(x) = o + x − ½x²ε; per punti su una retta in una base spaziale P(x)·P(y) = ½|x − y|².',
      ptsCols: ['x', 'P(x) = o + x + ½|x|² ε', ...PTS.map(v => `P(x)·P(${v})`)],
      motionsH: 'Moti come prodotti di specchi', motionsCols: ['moto', 'versore', 'specchi', 'verificato'],
      motionsRows: [
        ['traslazione di t', '1 + ½ t ε', '2 piani paralleli', 'translation'], ['rotazione', 'a b (due vettori della base)', '2 piani per un punto', 'rotation'],
        ['dilatazione', '1 + u e_p e_m', '2 sfere concentriche', 'dilation'], ['inversione in una sfera', 'P(c) − ½r²ε', '1 sfera', 'inversion'], ['riflessione in un piano', 'n + δε', '1 piano', 'plane']],
      motionsNote: 'Ogni riga è un sandwich su P(x), esatto su punti razionali casuali. Due piani paralleli si moltiplicano in una traslazione, due sfere concentriche in una dilatazione, e ogni isometria di R^n è al massimo n + 1 specchi-piano: uno riporta a casa l’origine, poi Cartan–Dieudonné del passo 8 finisce il lavoro. I vettori nulli ε e o non sono specchi: a·a = 0.',
      viewsH: n => `Tutte le viste a n = ${n}`,
      views: r => {
        const n = r.n_value, c = CN[n], tg = ['checked', 'standard'];
        const cl = { h: 'Clifford', t: `Un generatore in più di quadrato s dà ${c.ladder_generators} bivettori e [B_an, B_bn] = −2s B_ab; s = 0 è l’algebra degenere con ${c.pga_dimension} lame (PGA). Una coppia nulla dà ${c.cga_dimension} lame, e Cl(p+1,q+1) = Cl(p,q) ⊗ M₂(ℝ): quattro coppie danno M₁₆(ℝ). Esatto per n da 2 a 6 (coppia nulla n da 2 a 4); numpy concorda.`, tags: tg };
        const cu = { h: 'Cubo e semicubo', t: `Il generatore in più è un bit in più: il cubo ha ${1 << (n + 1)} vertici e le ${c.pga_dimension} lame della PGA sono i suoi vertici. La coppia nulla sono due bit in più: ${c.cga_dimension} vertici. I piani necessari per muovere un punto sono al massimo ${c.planes_to_move_a_point} = n + 1, uno in più degli specchi del passo 8.`, tags: ['checked', 'ours'] };
        const si = { h: 'Simplesso', t: `${n + 1} assi sono i vertici di un simplesso con ${c.ladder_generators} spigoli: ${C2(n)} dentro la base (rotazioni o boost) e ${n} che congiungono l’asse in più. Con la coppia nulla ci sono ${n + 2} vertici e ${c.conformal_generators} spigoli: ${C2(n)} ${pe(C2(n), 'rotazione', 'rotazioni')}, ${n} traslazioni, ${n} trasformazioni conformi speciali e lo spigolo tra ε e o, la dilatazione. Sono raggruppati in modo diverso, non rinominati: una traslazione è e_i e_p + e_i e_m, somma di due spigoli.`, tags: ['checked', 'ours'] };
        const la = { h: 'Etichette', t: `T_i = e_i ε (traslazioni), K_i = e_i o (conformi speciali), D = e_p e_m (dilatazione) e B_ij (rotazioni). Sotto il commutatore la dilatazione scala T di +2 e K di −2, esattamente: [D, T] = 2T e [D, K] = −2K. Le etichette sono notazione.`, tags: ['checked', 'standard'] };
        const ma = { h: 'Maxwell', t: `Le equazioni di Maxwell in quattro dimensioni sono conformemente invarianti: standard, non ricostruito qui. Ciò che è verificato è il gruppo che agirebbe: ${c.conformal_generators} generatori in ${n} dimensioni, che contengono i ${c.euclid_generators} di Euclide o Poincaré.`, tags: ['standard'] };
        const ym = { h: 'Yang–Mills (passo 4)', t: `Yang–Mills classica in quattro dimensioni è conformemente invariante: standard, non ricostruito qui. Gli stessi ${c.conformal_generators} generatori agiscono sullo spazio di base, non sull’indice interno.`, tags: ['standard'] };
        const di = { h: 'Dirac', t: `L’equazione di Dirac senza massa è conformemente invariante, e il termine di massa rompe la dilatazione: standard, non ricostruito qui. La sottoalgebra di Poincaré con ${c.euclid_generators} generatori è quella che sopravvive con la massa. Niente è risolto.`, tags: ['standard', 'open'] };
        return [cl, cu, si, la, ma, ym, di];
      },
      idH: 'Cosa è stato verificato, e dove', idCols: ['n', 'scala s = 0, ±1', 'coppia nulla, punti', 'traslazione, rotazione, dilatazione, inversione, piano', 'PGA dentro CGA', 'specchi-piano ≤ n + 1', 'algebra conforme'],
      idNote: 'Entrambe le basi. Scala: chiusura, Jacobi, quadrati, commutatori, forma di Killing, contrazione (n da 2 a 6). Coppia nulla e moti: n da 2 a 4. PGA dentro CGA: un omomorfismo iniettivo di algebre su tutte le coppie di elementi di base (n = 2, 3). Specchi-piano: n = 2, 3. Algebra conforme: C(n+2,2) generatori, chiusura, segnatura di Killing (n da 2 a 4). Aritmetica razionale esatta.',
      dblH: 'Due generatori in più, un fattore M₂(ℝ)', dblCols: ['coppie k', 'algebra Cl(k,k)', 'dimensione delle matrici', 'dimensione'],
      dblNote: 'Matrici reali esplicite: ogni coppia nulla raddoppia la taglia e i prodotti dei generatori restano una base di tutte le matrici, quindi Cl(k,k) è l’intera algebra di matrici di taglia 2^k, fino a M₁₆(ℝ) a k = 4 (il rango è calcolato modulo un primo, e può solo sottostimarlo). È il fattore per cui Cl(p+4,q+4) differisce da Cl(p,q): il ripetersi dei tipi ogni quattro coppie, non un muro.',
      xrH: 'Cosa ogni vista insegna alle altre',
      xr: [
        ['ours', 'Cubo → bit in più. La stessa regola dei bit: un generatore in più è un bit in più di quadrato 0, −1 o +1, e la coppia nulla sono due bit (−1, +1). Leggerli come bit del cubo è nostro; le geometrie sono da manuale.'],
        ['checked', 'Passo 7 → passo 9. La costante del generatore in più è quella del passo 7: metà di −2s è il coefficiente k = −s di e∧e nella curvatura. Poincaré, de Sitter e anti-de Sitter hanno tutti C(n+1,2) generatori.'],
        ['checked', 'Passo 8 → passo 9. Piani e sfere sono vettori non nulli, quindi sono specchi; le isometrie di R^n sono prodotti di al massimo n + 1 di essi. I vettori nulli ε e o non sono specchi, ed è per questo che il caso degenere aveva bisogno di una pagina a parte.'],
        ['standard', 'Le tre algebre basate sui piani (Euclide R^{d,0,1}, ellittica R^{d+1,0,0}, iperbolica R^{d,1,0}) e l’estensione alle sfere sono come le descrive l’articolo di Dorst e De Keninck, che abbiamo letto. Che le equazioni del moto siano le stesse nelle tre è affermato lì e attribuito a Gunn; non l’abbiamo ricavato di nuovo. Non abbiamo confrontato con gli altri trattamenti.']
      ],
      matH: 'Verifica indipendente con matrici',
      mat: 'Con matrici gamma di Jordan–Wigner (numpy), per entrambe le basi e n da 2 a 4: ε e o sono nilpotenti con εo + oε = 2, P(x) è nullo e P(x)P(y) + P(y)P(x) = −(x−y)², e traslazione, rotazione, dilatazione, inversione e riflessione in un piano mandano P(x) nel punto atteso. I commutatori [B_an, B_bn] = −2s B_ab valgono per s = ±1 (n da 2 a 5) e si annullano per s = 0, dove il generatore in più è la matrice nilpotente ε. I 2^(n+1) prodotti dei gamma della base e di ε sono matrici indipendenti, quindi la PGA è rappresentata fedelmente. L’algebra conforme si chiude e la sua forma di Killing ha (assi +1)(assi −1) autovalori positivi. Le versioni sbagliate falliscono: il segno opposto in P(x), o sostituito da −o, il coefficiente di traslazione 1 invece di ½, una coppia di segni uguali (ε non è più nullo), e uno specchio in ε, la cui matrice è singolare.',
      open: [
        ['open', 'La dinamica. Forza e forque, e le equazioni di Newton–Eulero, sono il passo successivo e non sono qui. Che le equazioni del moto coincidano nelle tre PGA è citato, non ricavato di nuovo; la dinamica conforme non è sviluppata nella fonte che abbiamo letto.'],
        ['open', 'Se tutto questo abbia un ruolo fisico nel modello. Il generatore in più è una geometria, non un campo.'],
        ['open', 'Niente di quanto qui scelga tre generazioni.']
      ],
      dl: { h: 'Verificalo tu', text: 'Due file Python. Il primo (solo libreria standard, con mirrors_selfcheck.py accanto) ricostruisce tutto quanto sopra, in modo esatto. Il secondo (richiede numpy) confronta con matrici esplicite ed esegue versioni sbagliate che devono fallire.', py: 'Scarica projective_selfcheck.py', py2: 'Scarica projective_matrix_check.py', json: 'Scarica projective.json', cmd: 'python3 projective_selfcheck.py --compare projective.json   ·   python3 projective_matrix_check.py --compare projective_matrix.json' }
    }
  }
};
export default COPY;
