import K from './springData.js';

// Copy for step 12 of the equations page (English and Italian): a spring on the cube. Every count comes from selfcheck/spring.json (exact rational arithmetic, standard library).
const S = K.summary, ROWN = K.rows.length, CL = K.clifford;
export const THREADS = ['oscillator', 'vertices', 'edges', 'faces', 'sign', 'labels'];
// where each row of the check lives, and whether the identity is textbook (standard) or the arrangement is ours
export const ROW_META = {
  A1: ['oscillator', 'standard'], A2: ['oscillator', 'standard'], A3: ['oscillator', 'standard'], A4: ['oscillator', 'standard'],
  B1: ['edges', 'standard'], B4: ['edges', 'standard'], B5: ['vertices', 'standard'], B6: ['vertices', 'standard'],
  C1: ['vertices', 'standard'], C2: ['vertices', 'standard'], C3: ['vertices', 'standard'], C4: ['vertices', 'standard'],
  B2: ['faces', 'standard'], B3: ['faces', 'standard'], B7: ['faces', 'standard'], B8: ['faces', 'standard'],
  D1: ['sign', 'standard'], D2: ['sign', 'ours'], D3: ['sign', 'standard'], D4: ['sign', 'standard'], D5: ['sign', 'ours'],
  E1: ['labels', 'ours'],
};
export const CONTROLS = ['A4', 'B8', 'C3'];
const ROWS = {
  A1: { en: ['Three motions: with u² = a, v² = b the phase vector s = xu + qv follows s′ = ωBs, B² = −ab, so x″ = −ab·ω²x. The power series equals cos, cosh or a straight line.', 'Exact power series to order 12 for (a,b) = (1,1), (1,−1), (0,1), compared coefficient by coefficient with the closed form.'],
    it: ['Tre moti: con u² = a, v² = b il vettore di fase s = xu + qv segue s′ = ωBs, B² = −ab, quindi x″ = −ab·ω²x. La serie di potenze coincide con cos, cosh o una retta.', 'Serie di potenze esatta fino all’ordine 12 per (a,b) = (1,1), (1,−1), (0,1), confrontata coefficiente per coefficiente con la forma chiusa.'] },
  A2: { en: ['For the spring, s² = x² + q² is a scalar and does not change in time: it is the energy.', 'Every coefficient of t¹ … t¹² of s(t)² vanishes (x₀ = 3, q₀ = 5, s² = 34).'],
    it: ['Per la molla, s² = x² + q² è uno scalare e non cambia nel tempo: è l’energia.', 'Ogni coefficiente di t¹ … t¹² di s(t)² si annulla (x₀ = 3, q₀ = 5, s² = 34).'] },
  A3: { en: ['The sandwich R s R̃ with the half angle R = exp(ωtB/2) gives the same motion as s′ = ωBs: the double cover again.', 'Series to order 12; the sandwich turns s by the full angle ωt although R carries ωt/2.'],
    it: ['Il sandwich R s R̃ con l’angolo metà R = exp(ωtB/2) dà lo stesso moto di s′ = ωBs: di nuovo il doppio rivestimento.', 'Serie fino all’ordine 12; il sandwich ruota s dell’angolo intero ωt benché R porti ωt/2.'] },
  A4: { en: ['Negative control: the sandwich with the full angle runs twice as fast and does not reproduce the oscillator.', 'The two series differ.'],
    it: ['Controllo negativo: il sandwich con l’angolo intero va al doppio della velocità e non riproduce l’oscillatore.', 'Le due serie differiscono.'] },
  B1: { en: ['Counts of the n-cube: 2ⁿ vertices, n·2ⁿ⁻¹ edges, C(n,2)·2ⁿ⁻² faces.', 'n = 2, 3, 4, 5: (4, 4, 1), (8, 12, 6), (16, 32, 24), (32, 80, 80).'],
    it: ['Conteggi dell’n-cubo: 2ⁿ vertici, n·2ⁿ⁻¹ spigoli, C(n,2)·2ⁿ⁻² facce.', 'n = 2, 3, 4, 5: (4, 4, 1), (8, 12, 6), (16, 32, 24), (32, 80, 80).'] },
  B4: { en: ['The spring matrix ∂₁∂₁ᵀ is the graph Laplacian n·I − adjacency.', 'Compared entry by entry for n = 2…5.'],
    it: ['La matrice delle molle ∂₁∂₁ᵀ è il laplaciano del grafo n·I − adiacenza.', 'Confronto elemento per elemento per n = 2…5.'] },
  B5: { en: ['Every Walsh vector is a normal mode with ω² = 2|s| (k = m = 1); the level ω² = 2j has multiplicity C(n,j).', 'The eigen-equation Lw = 2|s|w holds for all 2ⁿ masks, n = 2…5.'],
    it: ['Ogni vettore di Walsh è un modo normale con ω² = 2|s| (k = m = 1); il livello ω² = 2j ha molteplicità C(n,j).', 'L’equazione agli autovalori Lw = 2|s|w vale per tutte le 2ⁿ maschere, n = 2…5.'] },
  B6: { en: ['Independent check of the multiplicities: they are the nullities of L − 2j·I.', 'Rank by exact elimination over the rationals.'],
    it: ['Controllo indipendente delle molteplicità: sono le nullità di L − 2j·I.', 'Rango per eliminazione esatta sui razionali.'] },
  B2: { en: ['The boundary of a face has no boundary: ∂₁∂₂ = 0. The faces close up.', 'Integer matrix product, n = 2…5.'],
    it: ['Il bordo di una faccia non ha bordo: ∂₁∂₂ = 0. Le facce si chiudono.', 'Prodotto di matrici intere, n = 2…5.'] },
  B3: { en: ['Betti numbers of the vertex–edge–face complex: b₀ = 1, b₁ = 0, and V − E + F = b₀ − b₁ + b₂.', 'Ranks over the rationals; b₂ = 0, 1, 7, 31 for n = 2…5.'],
    it: ['Numeri di Betti del complesso vertici–spigoli–facce: b₀ = 1, b₁ = 0 e V − E + F = b₀ − b₁ + b₂.', 'Ranghi sui razionali; b₂ = 0, 1, 7, 31 per n = 2…5.'] },
  B7: { en: ['The stretch of any displacement adds to zero around every face (compatibility).', 'A fixed integer displacement, every face, n = 2…5.'],
    it: ['L’allungamento di qualunque spostamento somma a zero attorno a ogni faccia (compatibilità).', 'Uno spostamento intero fisso, ogni faccia, n = 2…5.'] },
  B8: { en: ['Negative control: an arbitrary edge field does not close around the faces.', 'At least one face has a non-zero sum.'],
    it: ['Controllo negativo: un campo arbitrario sugli spigoli non si chiude attorno alle facce.', 'Almeno una faccia ha somma non nulla.'] },
  C1: { en: ['The exact power-series solution of x″ = −Lx conserves the spring energy.', 'Every coefficient of t¹ … t¹³ of E vanishes for n = 3 (the series is cut at t¹⁴).'],
    it: ['La soluzione esatta in serie di potenze di x″ = −Lx conserva l’energia delle molle.', 'Ogni coefficiente di t¹ … t¹³ di E si annulla per n = 3 (la serie è troncata a t¹⁴).'] },
  C2: { en: ['A single mode oscillates as cos(√(2|s|) t).', 'The series of the solution equals the cosine series, mode 101 of the 3-cube.'],
    it: ['Un singolo modo oscilla come cos(√(2|s|) t).', 'La serie della soluzione coincide con la serie del coseno, modo 101 del 3-cubo.'] },
  C3: { en: ['Negative control: a network that breaks Newton’s third law (a vertex is pushed but does not push back, L not symmetric) does not conserve energy.', 'Some coefficient of t¹ … t¹³ is non-zero.'],
    it: ['Controllo negativo: una rete che viola la terza legge di Newton (un vertice è spinto ma non spinge a sua volta, L non simmetrica) non conserva l’energia.', 'Qualche coefficiente di t¹ … t¹³ non è nullo.'] },
  C4: { en: ['Plucking one vertex: x(t) = 2⁻ⁿ Σ_s w_s(v) cos(√(2|s|) t) w_s agrees with the exact series.', 'Coefficient by coefficient, t⁰ … t¹⁴, n = 3, vertex 101.'],
    it: ['Pizzicare un vertice: x(t) = 2⁻ⁿ Σ_s w_s(v) cos(√(2|s|) t) w_s coincide con la serie esatta.', 'Coefficiente per coefficiente, t⁰ … t¹⁴, n = 3, vertice 101.'] },
  D1: { en: ['D = Σ e_i (left multiplications) is symmetric and D² = n·I: the cross terms cancel because the generators anticommute.', 'Matrices of size 2ⁿ, n = 2…5, all squares +1.'],
    it: ['D = Σ e_i (moltiplicazioni a sinistra) è simmetrica e D² = n·I: i termini misti si annullano perché i generatori anticommutano.', 'Matrici di dimensione 2ⁿ, n = 2…5, tutti i quadrati +1.'] },
  D2: { en: ['The product of the four signs around every face is −1 (flux π); for the plain spring it is +1.', 'All 1, 6, 24, 80 faces, n = 2…5.'],
    it: ['Il prodotto dei quattro segni attorno a ogni faccia è −1 (flusso π); per la molla semplice è +1.', 'Tutte le 1, 6, 24, 80 facce, n = 2…5.'] },
  D3: { en: ['K = n·I − D satisfies K² − 2nK + (n² − n)I = 0 and tr D = 0: two levels, n ± √n, each 2ⁿ⁻¹ times.', 'The quadratic identity as an integer matrix equation, n = 2…5.'],
    it: ['K = n·I − D soddisfa K² − 2nK + (n² − n)I = 0 e tr D = 0: due livelli, n ± √n, ciascuno 2ⁿ⁻¹ volte.', 'L’identità quadratica come equazione di matrici intere, n = 2…5.'] },
  D4: { en: ['The signed network also conserves its energy.', 'Exact power series through t¹³, n = 3.'],
    it: ['Anche la rete con segni conserva la propria energia.', 'Serie di potenze esatta fino a t¹³, n = 3.'] },
  D5: { en: ['The signed matrix is a spring energy: xᵀKx = Σ over edges of (x_i − s_ij x_j)², with s_ij the sign of the generator; the plain one has every s_ij = +1.', 'A fixed integer vector, n = 2…5.'],
    it: ['La matrice con segni è un’energia di molle: xᵀKx = Σ sugli spigoli di (x_i − s_ij x_j)², con s_ij il segno del generatore; quella semplice ha ogni s_ij = +1.', 'Un vettore intero fisso, n = 2…5.'] },
  E1: { en: ['Conjugation of e_x by an even blade e_m is the Walsh character (−1)^{|x∧m|}; by an odd blade it is that character times (−1)^{|x|}.', 'All 256 pairs (m, x) of Cl(4,0).'],
    it: ['La coniugazione di e_x con una lama pari e_m è il carattere di Walsh (−1)^{|x∧m|}; con una lama dispari è quel carattere per (−1)^{|x|}.', 'Tutte le 256 coppie (m, x) di Cl(4,0).'] },
};
export const rowText = (lang, id) => { const r = ROWS[id][lang === 'it' ? 'it' : 'en']; return { claim: r[0], inst: r[1] }; };
export const rowIds = K.rows.map(r => r.id);

const COPY = {
  en: {
    s: {
      title: 'A spring on the cube: vertices, edges, faces and the rotor',
      lede: `Take the cube we have drawn since page 1 and make it a machine: a unit mass on every vertex, a Hooke spring on every edge, and each mass free to move along one line. Vertices are the blades, edges are multiplication by a generator, faces are the planes of the bivectors, so the three lenses of the cube become three parts of mechanics: the masses, the springs, and the rule that the stretches close up around a face. The rotor that turned planes in the earlier steps now runs an oscillator. Everything here is checked in exact arithmetic (${S.ok} claims in ${ROWN} rows). Hooke’s law, the spectrum of the cube and the signed matrix are standard; what is ours is the arrangement and three readings, tagged where they appear.`,
      ladderH: 'Three lenses and a rotor',
      ladder: [
        { k: 'Vertices', g: 'x_i', say: 'The 2ⁿ blades. One displacement and one unit mass each. The stiffness matrix L = n·I − adjacency.' },
        { k: 'Edges', g: 'x_a − x_b', say: 'The n·2ⁿ⁻¹ springs, one per multiplication by a generator. The energy is ½ Σ stretch².' },
        { k: 'Faces', g: 'Σ around = 0', say: 'The C(n,2)·2ⁿ⁻² planes of the bivectors. The stretches close up; with the signs of the product the flux is π.' },
        { k: 'The rotor', g: 's′ = ωBs', say: 'B = uv with B² = −1, +1 or 0: oscillator, inverted oscillator, free motion. The three kinds of i of step 11.' },
      ],
      ladderCap: 'The same cube carries Maxwell’s incidences, the Dirac edges and the commutator graph; here it carries a spring network. Nothing about the cube changes, only what we call a vertex, an edge and a face.',
      which: 'Which lens here', views: { mech: 'In mechanics', cube: 'On the cube', alg: 'In the algebra' },
      jumpLbl: 'Jump to a thread',
      threads: {
        oscillator: { h: 'One spring, one rotor', q: 'Is an oscillator already a rotation, and what happens when the sign of the square changes?', which: 'Second kind of i (B = uv) with the unit squares (+,+), (+,−) and (0,+).',
          mech: 'A mass on a Hooke spring obeys x″ = −ω²x. Put q = p/(mω): the state (x, q) goes round a circle and x² + q² (the energy up to a factor) does not change. If the force pushes away instead of back, x″ = +ω²x and the orbit is a hyperbola; with no spring the orbit is a straight line.',
          cube: 'One edge with its two vertices is the smallest network (n = 1). Its two displacements make one relative coordinate, and that coordinate is the oscillator above with ω² = 2: the level j = 1 of the cube.',
          alg: 'Put s = xu + qv in the algebra with u² = a, v² = b, and B = uv. Then s′ = ωBs and B² = −ab. With (+,+) B² = −1 and the solution is cos and sin; with (+,−) B² = +1 and it is cosh and sinh; with (0,+) B² = 0 and it is a line. A rotor R = e^{ωtB/2} in the sandwich R s R̃ turns s by the full angle ωt: it needs the half angle (the double cover again), and the full angle runs twice as fast.' },
        vertices: { h: 'Vertices carry the masses', q: 'How does a whole network of masses move, and which motions are pure tones?', which: 'Blades as vertices; the generator e_i as the step along edge i.',
          mech: 'Masses x_i on the vertices of a network obey x″ = −Lx with L the stiffness matrix. A normal mode is a pattern that moves as one cosine at its own frequency; every motion is a sum of modes, and the energy ½|x′|² + ½xᵀLx is constant.',
          cube: 'The 2ⁿ vertices are the n-bit strings and L = n·I − adjacency: each mass is pulled by its n neighbours. The Walsh vectors w_s(x) = (−1)^{|x∧s|} are the modes with ω² = 2|s|, where |s| is the number of ones, so the level ω² = 2j has multiplicity C(n,j). Pluck vertex v and every mode enters, level j carrying the share C(n,j)/2ⁿ of |x(0)|².',
          alg: 'Multiplying a blade e_x by the generator e_i moves it along edge i, with a sign. Dropping the signs gives the adjacency matrix and the classical spectrum of the cube; keeping them gives the matrix of thread 5. For the plain spring the algebra supplies only the vertex set and the edges, and the spectrum is classical.' },
        edges: { h: 'Edges carry the springs', q: 'Where does the energy live, and what is the stiffness matrix made of?', which: 'An edge is multiplication by one generator.',
          mech: 'A spring stores ½ (stretch)², and the stretch is the difference of the two end displacements. Collect the stretches in one vector s = ∂₁ᵀx. The total energy is ½|s|² and the stiffness matrix is L = ∂₁∂₁ᵀ, so it is symmetric and non-negative by construction (Newton’s third law).',
          cube: 'There are n·2ⁿ⁻¹ edges: 4, 12, 32, 80 for n = 2…5. ∂₁ is the vertex–edge incidence matrix: each column has one +1 and one −1.',
          alg: 'All 2ⁿ⁻¹ edges of direction i are the same left multiplication by e_i, and the n directions are the n generators. In thread 5 the sign of that multiplication becomes part of the spring.' },
        faces: { h: 'Faces carry the closure', q: 'Can the stretches be anything, or are they tied together?', which: 'A face is the plane of a bivector e_i e_j.',
          mech: 'A network stretches in a compatible way when the stretches come from displacements: around any closed loop of springs they add to zero, like the strain in an elastic body with no tears or dislocations. A field of stretches that does not close cannot come from any displacement.',
          cube: `The faces are the squares: C(n,2)·2ⁿ⁻² of them. Filled in, the boundary of a face has no boundary, ∂₁∂₂ = 0, and the filled cube has no one-dimensional hole (b₁ = 0 for n = 2…5), so every closed edge field is the stretch of some displacement. The widget tries a real displacement and an arbitrary field.`,
          alg: 'Walking round a face uses e_i, e_j, e_i, e_j in turn. For generators of square +1 that anticommute, the four signs multiply to −1: the Clifford product turns the loop into a half-turn of sign. This is the content of thread 5.' },
        sign: { h: 'The Clifford network: the same edges, with the sign of the generator', q: 'What changes if every spring is tied to a generator and carries its sign?', which: 'The Clifford product of step 1, all squares +1.',
          mech: 'A spring may join a mass to the reversed coordinate of its neighbour: energy ½(x_i − s x_j)² with s = ±1. The signs form a Z₂ connection; the product of the four signs around a face is its flux, and +1 against −1 is a physical difference (a frustrated network, as in a spin glass or the π-flux lattice).',
          cube: 'Keep the same n·2ⁿ⁻¹ edges and give each the sign that multiplication by its generator produces. The flux through every face is −1, where the plain network has +1. The stiffness matrix is K = n·I − D with D² = n·I, so only two levels remain, n − √n and n + √n, each 2ⁿ⁻¹ times, in place of n + 1 levels. Same trace n·2ⁿ either way.',
          alg: 'D = Σ e_i (left multiplication) is symmetric, D² = n·I because the cross terms cancel (the generators anticommute) and tr D = 0. This is the signed hypercube matrix Hao Huang used in 2019 for the sensitivity conjecture, so the algebra is standard. Reading its signs as flux π through the faces is ours. At n = 4 the two levels are 2 and 6 because 4 is a perfect square; that is arithmetic, not a result.' },
        labels: { h: 'The labels of step 11 are the normal modes', q: 'Is there a link between the labels that classify spinors and the modes of the spring?', which: 'Second kind (b_j) and the conjugation label of step 11.',
          mech: 'The mode with pattern w_s(x) = (−1)^{|x∧s|} has ω² = 2|s|: the more ones in s, the faster the pattern alternates and the higher the tone.',
          cube: 'The pattern is a sign on every vertex of the cube, a character of the group (ℤ₂)ⁿ.',
          alg: 'Conjugating the blade e_x by an even blade e_m gives (−1)^{|x∧m|}·e_x, so the label of step 11 is this character; for an odd blade it is the character of the complement. The labels of the spinor paper therefore classify the normal modes of the cube, and ω² = 2 × the number of mirrors in the versor e_m. The identity is arithmetic (checked); what a spinor label means as a vibration is open.' },
      },
      w: {
        osc: { h: 'Three kinds of i as three motions', lede: 'Choose the signs of the two generators u and v. The page computes B = uv in the bit-rule algebra, its square, and the motion of s = xu + qv under s′ = ωBs, with ω = 1. The dot is the state, the curve its orbit.',
          kindLbl: 'Kind of motion', kinds: { harmonic: 'Spring (+, +)', inverted: 'Inverted spring (+, −)', free: 'Free (0, +)' },
          sig: (a, b, B) => `u² = ${String(a).replace('-', '−')}, v² = ${String(b).replace('-', '−')} → B = uv, B² = ${String(B).replace('-', '−')}`, slider: 'Time',
          cap: 'Phase plane: x across, q up. Circle, hyperbola or straight line, from B² = −1, +1, 0.',
          law: k => `x″ = ${k}·x`, val: (x, q) => `x = ${x}, q = ${q}`,
          half: 'The sandwich with the half angle R = exp(ωtB/2) reproduces the motion', full: 'the sandwich with the full angle does not',
          energy: e => `s² = x² + q² = ${e}, the same at every time.` },
        cube: { h: 'Modes and plucking on the cube', lede: 'Unit masses on the vertices, unit springs on the edges. Either pick one normal mode (the n bits set a pattern of signs) or pluck one vertex and watch every mode come in. A dot above rest is blue, below is amber.',
          nLbl: 'Cube size', viewLbl: 'What to show', views: { mode: 'One mode', pluck: 'Pluck a vertex' }, bitsLbl: 'Bits of the mask s', bit: i => `bit ${i}`, slider: 'Time', play: 'Play', pause: 'Pause',
          cap: 'Vertices of the n-cube drawn flat; each dot moves up and down by its displacement. Springs are the edges.',
          capMode: 'One normal mode: every vertex moves as the same cosine, with the sign of the Walsh pattern.', capPluck: 'Vertex pulled up at t = 0, others at rest. Click a vertex to pluck a different one.',
          modeInfo: (s, j, w2, m) => `mask s = ${s}, |s| = ${j}, ω² = 2|s| = ${w2}; this level has ${m} modes.`,
          pluckInfo: v => `Plucked vertex ${v}. At t = 0 only it is displaced, and the motion is the sum of all modes.`,
          econs: (e, e0) => `Energy now ${e}, at t = 0 ${e0}`,
          shareCols: ['ω² of the level', 'modes', 'share of |x(0)|²'] },
        spec: { h: 'Spectra: the plain spring and the Clifford spring', lede: 'The squared frequencies of the same cube with the plain springs (top) and with the springs carrying the sign of the generator (bottom). The area of a dot is proportional to its multiplicity, the number printed above it.',
          nLbl: 'Cube size', plain: 'Plain', signed: 'Clifford (signed)', cap: 'Squared frequency ω² on one scale. Same number of modes and same total stiffness in both rows.',
          plainLine: (k, w, m) => `Plain: ${k} levels, ω² = ${w}, with multiplicities ${m}.`,
          signedLine: (k, a, b, m) => `Clifford: ${k} levels, ω² = ${a} and ${b}, each ${m} times.`,
          trace: (m1, m2, t1, t2, tt) => `Modes ${m1} and ${m2} (= 2ⁿ); sum of ω² ${t1} and ${t2} (= n·2ⁿ = ${tt}).` },
        face: { h: 'Faces close the stretches', lede: 'Choose a real displacement or an arbitrary field on the edges, and add the stretches around every face. A real displacement always sums to zero; an arbitrary field generally does not.',
          nLbl: 'Cube size', kindLbl: 'Edge field', kinds: { disp: 'Stretch of a displacement', field: 'An arbitrary field' }, again: 'New sample',
          counts: (v, e, f) => `${v} vertices, ${e} edges, ${f} faces.`, facesLbl: 'Sum around each face', faceTitle: nm => `face ${nm}: axes i j at the base vertex`,
          closed: 'Every face sums to zero: the stretches close up.', open: 'Some face does not sum to zero: this field is not the stretch of any displacement.',
          fluxH: 'The sign around a face', flux: (k, v) => `Clifford network: the product of the four signs around each of the ${k} faces is ${v} (flux π). The plain network has +1.`, fluxCap: 'Face labels read i j @ base vertex bits.' },
        lab: { h: 'A label is a normal mode', lede: 'Choose a blade e_m with the n bits. The page conjugates every blade e_x by it in the bit-rule algebra and compares the sign with the Walsh character; the same pattern is the vibration mode of the cube.',
          nLbl: 'Cube size', bitsLbl: 'Bits of the blade e_m', bit: i => `bit ${i}`, head: (m, k, w) => `m = ${m}: grade ${k}, ${w} blade.`, evenWord: 'an even', oddWord: 'an odd',
          cols: ['blade e_x', 'sign of e_m e_x e_m⁻¹', 'predicted sign'],
          mode: (s, w2, odd) => `Pattern = the mode with mask ${s}${odd ? ' (the complement of m, because m is odd)' : ''}, ω² = ${w2}.`, cap: 'Predicted = (−1)^{|x∧m|}, times (−1)^{|x|} when m is odd.' },
      },
      tabH: 'The cube in numbers', tabCols: ['n', 'vertices', 'edges', 'faces', 'b₀, b₁, b₂', 'levels ω² = 2j (multiplicity)', 'Clifford levels'],
      tabNote: 'All from the exact script. b₂ counts the closed surfaces the filled cube encloses.',
      mxH: 'The checks, one row at a time', mxLede: `${ROWN} rows, ${S.ok} claims, every one exact. Three rows are negative controls: they must fail on a wrong network, and they do. Each row can be run alone.`,
      searchPh: 'Search the rows', searchLbl: 'Search the rows', filterLbl: 'Filter by thread', mxCount: (a, b) => `${a} of ${b} rows`,
      all: 'All', status: { ok: 'checked' }, srcTag: { standard: 'standard', ours: 'ours' },
      labels: { claim: 'Claim', how: 'How it is checked', checks: 'claims', control: 'negative control', cmd: 'Run it', sections: 'Rows', nothing: 'No row matches.' },
      openH: 'What is established, and what is not',
      open: [
        ['checked', `All ${S.ok} claims: oscillator cases, the cube’s counts and topology, its normal modes, energy conservation, the signed network, and the label–mode identity.`],
        ['standard', 'Hooke’s law, the spectrum of the hypercube (Walsh functions), the compatibility of strain, circle–hyperbola–line from the three squares of B, and the signed matrix with D² = n·I (Huang, 2019).'],
        ['ours', 'The arrangement: masses, springs and closure as the three lenses of one cube; the reading of the signs as flux π through the faces; the reading of the step 11 labels as normal modes.'],
        ['open', 'One scalar displacement per vertex only; real springs need vector displacements. No rigid-body motion in this step (step 13 adds one), no continuum limit, no action principle, no damping or driving. Whether the signed network has anything to do with the Dirac operator on the demicube is open.'],
        ['open', 'The multiplicities 1, 3, 3, 1 at n = 3 are binomial coefficients and say nothing about three generations.'],
      ],
      next: 'Next on this road: step 13 treats the cube as a rigid body. What remains is a spring network with vector displacements (the zero modes should be the rigid motions), an action principle for the springs, and then lattice Maxwell with energy on the faces. See the Map page.',
      dl: { h: 'Download the check', text: 'The script uses only the standard library and exact fractions. Run it with no arguments to check everything, with --row B5 to run one row, or with --compare to check the data file.', py: 'spring_selfcheck.py', json: 'spring.json', cmd: 'python3 spring_selfcheck.py   ·   python3 spring_selfcheck.py --row B5   ·   python3 spring_selfcheck.py --compare spring.json' },
      mapLink: 'Open the Map page',
      numH: 'Numbers on this page', num: `Spring script: ${S.ok} claims in ${ROWN} rows, all hold; n = 2…5 for the cube, order 14 for the series, ${CL['3'].frequencies_squared.replace('+-', '±')} for the signed 3-cube.`,
    },
  },
  it: {
    s: {
      title: 'Una molla sul cubo: vertici, spigoli, facce e il rotore',
      lede: `Prendiamo il cubo che disegniamo dalla pagina 1 e facciamone una macchina: una massa unitaria su ogni vertice, una molla di Hooke su ogni spigolo, e ogni massa libera di muoversi su una retta. I vertici sono le lame, gli spigoli sono la moltiplicazione per un generatore, le facce sono i piani dei bivettori: le tre lenti del cubo diventano tre parti della meccanica, le masse, le molle e la regola che gli allungamenti si chiudono attorno a una faccia. Il rotore che girava i piani nei passi precedenti ora governa un oscillatore. Tutto è controllato in aritmetica esatta (${S.ok} affermazioni in ${ROWN} righe). La legge di Hooke, lo spettro del cubo e la matrice con segni sono standard; nostro è l’assetto e tre letture, segnalate dove compaiono.`,
      ladderH: 'Tre lenti e un rotore',
      ladder: [
        { k: 'Vertici', g: 'x_i', say: 'Le 2ⁿ lame. Ciascuna ha uno spostamento e una massa unitaria. La matrice di rigidità è L = n·I − adiacenza.' },
        { k: 'Spigoli', g: 'x_a − x_b', say: 'Le n·2ⁿ⁻¹ molle, una per ogni moltiplicazione per un generatore. L’energia è ½ Σ allungamento².' },
        { k: 'Facce', g: 'Σ attorno = 0', say: 'I C(n,2)·2ⁿ⁻² piani dei bivettori. Gli allungamenti si chiudono; con i segni del prodotto il flusso è π.' },
        { k: 'Il rotore', g: 's′ = ωBs', say: 'B = uv con B² = −1, +1 o 0: oscillatore, oscillatore invertito, moto libero. I tre tipi di i del passo 11.' },
      ],
      ladderCap: 'Lo stesso cubo porta le incidenze di Maxwell, gli spigoli di Dirac e il grafo dei commutatori; qui porta una rete di molle. Del cubo non cambia nulla, cambia solo che cosa chiamiamo vertice, spigolo e faccia.',
      which: 'Quale lente qui', views: { mech: 'In meccanica', cube: 'Sul cubo', alg: 'Nell’algebra' },
      jumpLbl: 'Vai a un filone',
      threads: {
        oscillator: { h: 'Una molla, un rotore', q: 'Un oscillatore è già una rotazione, e che cosa succede quando cambia il segno del quadrato?', which: 'Secondo tipo di i (B = uv) con i quadrati unitari (+,+), (+,−) e (0,+).',
          mech: 'Una massa su una molla di Hooke obbedisce a x″ = −ω²x. Con q = p/(mω) lo stato (x, q) gira su un cerchio e x² + q² (l’energia, a meno di un fattore) non cambia. Se la forza spinge via invece di richiamare, x″ = +ω²x e l’orbita è un’iperbole; senza molla l’orbita è una retta.',
          cube: 'Uno spigolo con i suoi due vertici è la rete più piccola (n = 1). I due spostamenti danno una coordinata relativa, e quella coordinata è l’oscillatore di sopra con ω² = 2: il livello j = 1 del cubo.',
          alg: 'Poniamo s = xu + qv nell’algebra con u² = a, v² = b, e B = uv. Allora s′ = ωBs e B² = −ab. Con (+,+) B² = −1 e la soluzione è coseno e seno; con (+,−) B² = +1 e sono cosh e sinh; con (0,+) B² = 0 ed è una retta. Un rotore R = e^{ωtB/2} nel sandwich R s R̃ ruota s dell’angolo intero ωt: serve l’angolo metà (ancora il doppio rivestimento), e l’angolo intero corre al doppio.' },
        vertices: { h: 'I vertici portano le masse', q: 'Come si muove una intera rete di masse, e quali moti sono toni puri?', which: 'Le lame come vertici; il generatore e_i come passo lungo lo spigolo i.',
          mech: 'Le masse x_i sui vertici di una rete obbediscono a x″ = −Lx con L la matrice di rigidità. Un modo normale è uno schema che si muove come un solo coseno alla propria frequenza; ogni moto è una somma di modi, e l’energia ½|x′|² + ½xᵀLx è costante.',
          cube: 'I 2ⁿ vertici sono le stringhe di n bit e L = n·I − adiacenza: ogni massa è tirata dai suoi n vicini. I vettori di Walsh w_s(x) = (−1)^{|x∧s|} sono i modi con ω² = 2|s|, dove |s| è il numero di uni, quindi il livello ω² = 2j ha molteplicità C(n,j). Pizzicando il vertice v entrano tutti i modi, e il livello j porta la quota C(n,j)/2ⁿ di |x(0)|².',
          alg: 'Moltiplicare una lama e_x per il generatore e_i la sposta lungo lo spigolo i, con un segno. Senza i segni si ha la matrice di adiacenza e lo spettro classico del cubo; con i segni si ha la matrice del filone 5. Per la molla semplice l’algebra fornisce solo l’insieme dei vertici e gli spigoli, e lo spettro è classico.' },
        edges: { h: 'Gli spigoli portano le molle', q: 'Dove vive l’energia, e di che cosa è fatta la matrice di rigidità?', which: 'Uno spigolo è la moltiplicazione per un generatore.',
          mech: 'Una molla immagazzina ½ (allungamento)², e l’allungamento è la differenza dei due spostamenti agli estremi. Raccogliamo gli allungamenti in un vettore s = ∂₁ᵀx. L’energia totale è ½|s|² e la matrice di rigidità è L = ∂₁∂₁ᵀ, quindi è simmetrica e non negativa per costruzione (terza legge di Newton).',
          cube: 'Gli spigoli sono n·2ⁿ⁻¹: 4, 12, 32, 80 per n = 2…5. ∂₁ è la matrice di incidenza vertici–spigoli: ogni colonna ha un +1 e un −1.',
          alg: 'Tutti i 2ⁿ⁻¹ spigoli di direzione i sono la stessa moltiplicazione a sinistra per e_i, e le n direzioni sono gli n generatori. Nel filone 5 il segno di quella moltiplicazione entra a far parte della molla.' },
        faces: { h: 'Le facce portano la chiusura', q: 'Gli allungamenti possono essere qualsiasi, o sono legati tra loro?', which: 'Una faccia è il piano di un bivettore e_i e_j.',
          mech: 'Una rete si allunga in modo compatibile quando gli allungamenti vengono da spostamenti: lungo ogni circuito chiuso di molle la somma è zero, come la deformazione di un corpo elastico senza strappi né dislocazioni. Un campo di allungamenti che non si chiude non può venire da alcuno spostamento.',
          cube: 'Le facce sono i quadrati: C(n,2)·2ⁿ⁻². Riempite, il bordo di una faccia non ha bordo, ∂₁∂₂ = 0, e il cubo riempito non ha buchi di dimensione uno (b₁ = 0 per n = 2…5), quindi ogni campo chiuso sugli spigoli è l’allungamento di qualche spostamento. Il widget prova uno spostamento vero e un campo arbitrario.',
          alg: 'Girare attorno a una faccia usa e_i, e_j, e_i, e_j in ordine. Per generatori di quadrato +1 che anticommutano, i quattro segni si moltiplicano a −1: il prodotto di Clifford trasforma il giro in una mezza rotazione del segno. È il contenuto del filone 5.' },
        sign: { h: 'La rete di Clifford: gli stessi spigoli, con il segno del generatore', q: 'Che cosa cambia se ogni molla è legata a un generatore e ne porta il segno?', which: 'Il prodotto di Clifford del passo 1, tutti i quadrati +1.',
          mech: 'Una molla può collegare una massa alla coordinata invertita del vicino: energia ½(x_i − s x_j)² con s = ±1. I segni formano una connessione Z₂; il prodotto dei quattro segni attorno a una faccia è il suo flusso, e +1 contro −1 è una differenza fisica (una rete frustrata, come in un vetro di spin o nel reticolo con flusso π).',
          cube: 'Teniamo gli stessi n·2ⁿ⁻¹ spigoli e diamo a ciascuno il segno che produce la moltiplicazione per il suo generatore. Il flusso attraverso ogni faccia è −1, dove la rete semplice ha +1. La matrice di rigidità è K = n·I − D con D² = n·I, quindi restano solo due livelli, n − √n e n + √n, ciascuno 2ⁿ⁻¹ volte, al posto di n + 1 livelli. La traccia n·2ⁿ è la stessa.',
          alg: 'D = Σ e_i (moltiplicazione a sinistra) è simmetrica, D² = n·I perché i termini misti si annullano (i generatori anticommutano) e tr D = 0. È la matrice dell’ipercubo con segni che Hao Huang ha usato nel 2019 per la congettura della sensibilità, quindi l’algebra è standard. Leggere i suoi segni come flusso π attraverso le facce è nostro. Per n = 4 i due livelli sono 2 e 6 perché 4 è un quadrato perfetto; è aritmetica, non un risultato.' },
        labels: { h: 'Le etichette del passo 11 sono i modi normali', q: 'C’è un legame tra le etichette che classificano gli spinori e i modi della molla?', which: 'Secondo tipo (b_j) e l’etichetta di coniugazione del passo 11.',
          mech: 'Il modo con schema w_s(x) = (−1)^{|x∧s|} ha ω² = 2|s|: più uni ci sono in s, più in fretta lo schema si alterna e più acuto è il tono.',
          cube: 'Lo schema è un segno su ogni vertice del cubo, un carattere del gruppo (ℤ₂)ⁿ.',
          alg: 'Coniugare la lama e_x con una lama pari e_m dà (−1)^{|x∧m|}·e_x, quindi l’etichetta del passo 11 è questo carattere; per una lama dispari è il carattere del complemento. Le etichette dell’articolo sugli spinori classificano dunque i modi normali del cubo, e ω² = 2 × il numero di specchi nel versore e_m. L’identità è aritmetica (controllata); che cosa significhi un’etichetta di spinore come vibrazione è aperto.' },
      },
      w: {
        osc: { h: 'Tre tipi di i come tre moti', lede: 'Scegli i segni dei due generatori u e v. La pagina calcola B = uv nell’algebra della regola dei bit, il suo quadrato e il moto di s = xu + qv sotto s′ = ωBs, con ω = 1. Il punto è lo stato, la curva la sua orbita.',
          kindLbl: 'Tipo di moto', kinds: { harmonic: 'Molla (+, +)', inverted: 'Molla invertita (+, −)', free: 'Libero (0, +)' },
          sig: (a, b, B) => `u² = ${String(a).replace('-', '−')}, v² = ${String(b).replace('-', '−')} → B = uv, B² = ${String(B).replace('-', '−')}`, slider: 'Tempo',
          cap: 'Piano delle fasi: x in orizzontale, q in verticale. Cerchio, iperbole o retta, da B² = −1, +1, 0.',
          law: k => `x″ = ${k}·x`, val: (x, q) => `x = ${x}, q = ${q}`,
          half: 'Il sandwich con l’angolo metà R = exp(ωtB/2) riproduce il moto', full: 'il sandwich con l’angolo intero no',
          energy: e => `s² = x² + q² = ${e}, uguale a ogni istante.` },
        cube: { h: 'Modi e pizzicata sul cubo', lede: 'Masse unitarie sui vertici, molle unitarie sugli spigoli. Scegli un modo normale (gli n bit fissano uno schema di segni) oppure pizzica un vertice e guarda entrare tutti i modi. Un punto sopra la quiete è blu, sotto è ambra.',
          nLbl: 'Dimensione del cubo', viewLbl: 'Che cosa mostrare', views: { mode: 'Un modo', pluck: 'Pizzica un vertice' }, bitsLbl: 'Bit della maschera s', bit: i => `bit ${i}`, slider: 'Tempo', play: 'Avvia', pause: 'Pausa',
          cap: 'I vertici dell’n-cubo disegnati in piano; ogni punto sale e scende del proprio spostamento. Le molle sono gli spigoli.',
          capMode: 'Un modo normale: ogni vertice si muove come lo stesso coseno, con il segno dello schema di Walsh.', capPluck: 'Vertice tirato su a t = 0, gli altri fermi. Clicca un vertice per pizzicarne un altro.',
          modeInfo: (s, j, w2, m) => `maschera s = ${s}, |s| = ${j}, ω² = 2|s| = ${w2}; questo livello ha ${m} modi.`,
          pluckInfo: v => `Vertice pizzicato ${v}. A t = 0 solo lui è spostato, e il moto è la somma di tutti i modi.`,
          econs: (e, e0) => `Energia ora ${e}, a t = 0 ${e0}`,
          shareCols: ['ω² del livello', 'modi', 'quota di |x(0)|²'] },
        spec: { h: 'Spettri: la molla semplice e la molla di Clifford', lede: 'Le frequenze al quadrato dello stesso cubo con le molle semplici (sopra) e con le molle che portano il segno del generatore (sotto). L’area di un punto è proporzionale alla molteplicità, il numero scritto sopra.',
          nLbl: 'Dimensione del cubo', plain: 'Semplice', signed: 'Clifford (con segni)', cap: 'Frequenza al quadrato ω² su un’unica scala. Stesso numero di modi e stessa rigidità totale nelle due righe.',
          plainLine: (k, w, m) => `Semplice: ${k} livelli, ω² = ${w}, con molteplicità ${m}.`,
          signedLine: (k, a, b, m) => `Clifford: ${k} livelli, ω² = ${a} e ${b}, ciascuno ${m} volte.`,
          trace: (m1, m2, t1, t2, tt) => `Modi ${m1} e ${m2} (= 2ⁿ); somma degli ω² ${t1} e ${t2} (= n·2ⁿ = ${tt}).` },
        face: { h: 'Le facce chiudono gli allungamenti', lede: 'Scegli uno spostamento vero o un campo arbitrario sugli spigoli e somma gli allungamenti attorno a ogni faccia. Uno spostamento vero dà sempre somma zero; un campo arbitrario in genere no.',
          nLbl: 'Dimensione del cubo', kindLbl: 'Campo sugli spigoli', kinds: { disp: 'Allungamento di uno spostamento', field: 'Un campo arbitrario' }, again: 'Nuovo campione',
          counts: (v, e, f) => `${v} vertici, ${e} spigoli, ${f} facce.`, facesLbl: 'Somma attorno a ogni faccia', faceTitle: nm => `faccia ${nm}: assi i j sul vertice base`,
          closed: 'Ogni faccia somma zero: gli allungamenti si chiudono.', open: 'Qualche faccia non somma zero: questo campo non è l’allungamento di alcuno spostamento.',
          fluxH: 'Il segno attorno a una faccia', flux: (k, v) => `Rete di Clifford: il prodotto dei quattro segni attorno a ciascuna delle ${k} facce è ${v} (flusso π). La rete semplice ha +1.`, fluxCap: 'Le etichette delle facce si leggono i j @ bit del vertice base.' },
        lab: { h: 'Un’etichetta è un modo normale', lede: 'Scegli una lama e_m con gli n bit. La pagina coniuga ogni lama e_x con essa nell’algebra della regola dei bit e confronta il segno con il carattere di Walsh; lo stesso schema è il modo di vibrazione del cubo.',
          nLbl: 'Dimensione del cubo', bitsLbl: 'Bit della lama e_m', bit: i => `bit ${i}`, head: (m, k, w) => `m = ${m}: grado ${k}, lama ${w}.`, evenWord: 'pari', oddWord: 'dispari',
          cols: ['lama e_x', 'segno di e_m e_x e_m⁻¹', 'segno previsto'],
          mode: (s, w2, odd) => `Schema = il modo con maschera ${s}${odd ? ' (il complemento di m, perché m è dispari)' : ''}, ω² = ${w2}.`, cap: 'Previsto = (−1)^{|x∧m|}, per (−1)^{|x|} quando m è dispari.' },
      },
      tabH: 'Il cubo in numeri', tabCols: ['n', 'vertici', 'spigoli', 'facce', 'b₀, b₁, b₂', 'livelli ω² = 2j (molteplicità)', 'livelli di Clifford'],
      tabNote: 'Tutto dallo script esatto. b₂ conta le superfici chiuse racchiuse dal cubo riempito.',
      mxH: 'I controlli, una riga alla volta', mxLede: `${ROWN} righe, ${S.ok} affermazioni, tutte esatte. Tre righe sono controlli negativi: devono fallire su una rete sbagliata, e falliscono. Ogni riga si può eseguire da sola.`,
      searchPh: 'Cerca nelle righe', searchLbl: 'Cerca nelle righe', filterLbl: 'Filtra per filone', mxCount: (a, b) => `${a} righe su ${b}`,
      all: 'Tutte', status: { ok: 'controllato' }, srcTag: { standard: 'standard', ours: 'nostro' },
      labels: { claim: 'Affermazione', how: 'Come si controlla', checks: 'affermazioni', control: 'controllo negativo', cmd: 'Eseguila', sections: 'Righe', nothing: 'Nessuna riga corrisponde.' },
      openH: 'Che cosa è stabilito e che cosa no',
      open: [
        ['checked', `Tutte le ${S.ok} affermazioni: i casi dell’oscillatore, i conteggi e la topologia del cubo, i suoi modi normali, la conservazione dell’energia, la rete con segni e l’identità etichetta–modo.`],
        ['standard', 'La legge di Hooke, lo spettro dell’ipercubo (funzioni di Walsh), la compatibilità della deformazione, cerchio–iperbole–retta dai tre quadrati di B, e la matrice con segni con D² = n·I (Huang, 2019).'],
        ['ours', 'L’assetto: masse, molle e chiusura come le tre lenti di un solo cubo; la lettura dei segni come flusso π attraverso le facce; la lettura delle etichette del passo 11 come modi normali.'],
        ['open', 'Solo uno spostamento scalare per vertice; le molle vere richiedono spostamenti vettoriali. Nessun moto rigido in questo passo (lo aggiunge il passo 13), nessun limite al continuo, nessun principio d’azione, nessuno smorzamento né forzante. Se la rete con segni c’entri qualcosa con l’operatore di Dirac sul demicubo è aperto.'],
        ['open', 'Le molteplicità 1, 3, 3, 1 per n = 3 sono coefficienti binomiali e non dicono nulla sulle tre generazioni.'],
      ],
      next: 'Avanti su questa strada: il passo 13 tratta il cubo come corpo rigido. Resta una rete di molle con spostamenti vettoriali (i modi nulli dovrebbero essere i moti rigidi), un principio d’azione per le molle, poi Maxwell sul reticolo con l’energia sulle facce. Vedi la pagina Mappa.',
      dl: { h: 'Scarica il controllo', text: 'Lo script usa solo la libreria standard e frazioni esatte. Eseguilo senza argomenti per controllare tutto, con --row B5 per una riga, o con --compare per controllare il file dei dati.', py: 'spring_selfcheck.py', json: 'spring.json', cmd: 'python3 spring_selfcheck.py   ·   python3 spring_selfcheck.py --row B5   ·   python3 spring_selfcheck.py --compare spring.json' },
      mapLink: 'Apri la pagina Mappa',
      numH: 'Numeri di questa pagina', num: `Script delle molle: ${S.ok} affermazioni in ${ROWN} righe, tutte valide; n = 2…5 per il cubo, ordine 14 per la serie, ${CL['3'].frequencies_squared.replace('+-', '±')} per il 3-cubo con segni.`,
    },
  },
};
export default COPY;
