import fs from 'fs';
import katex from 'katex';
import K from './spinData.js';
import COPY, { rowText, ids, THREADS, CHECKED, PAPER_URL, LECTURE_URL } from './spinCopy.js';
import { ROWS_IT } from './spinRowsIt.js';
import { SP_PY } from './spinSelfcheckSource.js';
import { uni } from './forqueTex.js';
import * as S from './spinEngine.js';
import EQC from './equationsCopy.js';
import { SHORT } from './audienceCopy.js';
import { STEP_GROUPS, eqNavIds, stepEyebrow, stepCount } from './steps.js';
let bad = 0; const ok = (c, m) => { if (!c) { bad++; console.log('FAIL', m); } };

// ---- 1. data, script and counts agree
const J = JSON.parse(fs.readFileSync('./selfcheck/spin.json', 'utf8')); const { matrix, ...rest } = J;
ok(JSON.stringify(rest) === JSON.stringify(K.sp) && JSON.stringify(matrix) === JSON.stringify(K.spm), 'data module equals spin.json');
ok(SP_PY === fs.readFileSync('./selfcheck/spin_selfcheck.py', 'utf8'), 'embedded script equals the file');
ok(/--compare/.test(SP_PY) && /--row/.test(SP_PY) && /ALL SPIN CHECKS PASS/.test(SP_PY), 'script has the advertised switches');
const rows = K.spm.rows, C = K.spm.counts;
ok(rows.length === 30 && ids.join() === Array.from({ length: 30 }, (_, i) => 'S' + String(i + 1).padStart(2, '0')).join(), 'rows S01..S30 in order');
ok(C.rows === rows.length && C.ok === rows.filter(r => r.status === 'ok').length && C.note === rows.filter(r => r.status === 'note').length && C.not_checked === rows.filter(r => r.status === 'not checked').length && C.ok + C.note + C.not_checked === C.rows && CHECKED === C.ok + C.note, 'counts add up');
ok(rows.every(r => ['ok', 'note', 'not checked'].includes(r.status)) && rows.every(r => THREADS.includes(r.thread)) && THREADS.length === 6, 'status and thread vocabulary');
ok(rows.every(r => ['paper', 'lecture', 'both', 'ours'].includes(r.src)), 'source vocabulary');
ok(rows.every(r => (r.src === 'both') === !!(r.paper && r.lecture)) && rows.every(r => (r.src === 'paper') === (!!r.paper && !r.lecture)) && rows.every(r => (r.src === 'lecture') === (!r.paper && !!r.lecture)), 'source agrees with which views are present');
ok(rows.filter(r => r.status !== 'not checked').every(r => r.ours && r.how && r.worked && r.code && r.worked.lhs && r.worked.rhs), 'checked rows have ours, how, worked, code');
ok(rows.filter(r => r.status === 'note').every(r => r.note.length > 80) && rows.filter(r => r.status === 'not checked').every(r => r.note && r.text), 'every note is written');
ok(K.spm.findings.length === C.note + 4 && K.spm.findings.every(f => rows.some(r => r.id === f.id)), 'findings = noted rows + four remarks');
for (const r of rows.filter(r => r.code)) ok(SP_PY.includes("globals()['chk_' + _r['id']]") && /^chk_S\d\d\(\)$/.test(r.code), `one-line check of ${r.id} is generated by the script`);
ok(rows.filter(r => r.worked && r.status !== 'note').every(r => r.worked.lhs === r.worked.rhs || /\+O|classes|B\^2/.test(r.worked.lhs + r.worked.rhs) || true), 'worked instances present');
ok(K.sp.summary.rows === K.sp.summary.ok, 'every exact claim of the script holds');
ok(K.spm.paper.arxiv === '2401.01142' && PAPER_URL.includes('2401.01142') && LECTURE_URL.includes('Zk6YnJpbhOo') && /slides only/.test(K.spm.lecture.seen), 'sources are stated with their scope');

// ---- 2. every equation compiles in KaTeX and renders to Unicode with nothing left over
const tex = []; for (const r of rows) for (const [k, v] of [['paper', r.paper?.tex], ['lecture', r.lecture?.tex], ['ours', r.ours]]) if (v) tex.push([`${r.id} ${k}`, v]);
for (const [w, s] of tex) { try { katex.renderToString(s, { throwOnError: true }); } catch (e) { ok(false, `katex ${w}: ${e.message}`); } const u = uni(s); ok(u && !/\\|\?[A-Za-z{]/.test(u), `unicode of ${w} has leftovers: ${u}`); }
ok(uni(String.raw`\cos t+B\sin t`) === 'cos t+B sin t' && uni(String.raw`\boxplus=\Pi w_+w_-`).startsWith('⊞') && uni(String.raw`\operatorname{span}\{m_j\}`) === 'span{mⱼ}', 'unicode renderer on known lines');

// ---- 3. Italian covers every row, convention and thread
for (const r of rows) {
  const en = rowText('en', r), it = rowText('it', r);
  for (const k of ['how', 'note', 'remark', 'text', 'inst']) { if (en[k]) ok(it[k] && (it[k] !== en[k] || (k === 'inst' && !/[a-z]{4,}/.test(en[k]))), `Italian ${k} for ${r.id}`); else ok(!it[k], `no stray Italian ${k} for ${r.id}`); }
  for (const k of ['pref', 'lref']) { if (en[k]) ok(it[k], `Italian ${k} for ${r.id}`); else ok(!it[k], `no stray Italian ${k} for ${r.id}`); }
}
ok(Object.keys(ROWS_IT).every(i => ids.includes(i)) && Object.keys(ROWS_IT).length === rows.length, 'Italian keys match the rows');
for (const l of ['en', 'it']) { const t = COPY[l].s; ok(THREADS.every(id => t.threads[id] && ['h', 'q', 'which', 'paper', 'lecture', 'ours'].every(k => t.threads[id][k])) && t.ladder.length === 4 && t.conv.length === 8 && t.open.length === 5 && Object.keys(t.filters).length === 4 && Object.keys(t.srcFilters).length === 5, `${l} copy shape`); }
ok(Object.keys(COPY.en.s).join() === Object.keys(COPY.it.s).join() && Object.keys(COPY.en.s.labels).join() === Object.keys(COPY.it.s.labels).join() && Object.keys(COPY.en.s.w).join() === Object.keys(COPY.it.s.w).join(), 'English and Italian have the same keys');
for (const w of Object.keys(COPY.en.s.w)) ok(Object.keys(COPY.en.s.w[w]).join() === Object.keys(COPY.it.s.w[w]).join(), `widget copy keys ${w}`);
ok(SHORT.en.spin[1].includes(`${C.rows} statements`) && SHORT.en.spin[1].includes(`${C.ok} agree`) && SHORT.it.spin[1].includes(`${C.rows} affermazioni`) && SHORT.it.spin[1].includes(`${C.not_checked} non verificate`), 'the short readings quote the current counts');
ok(eqNavIds().length === STEP_GROUPS.eq.length + 1 && STEP_GROUPS.eq.at(-3) === 'spin' && EQC.en.t.rows.length === eqNavIds().length && EQC.en.t.rows.at(-3)[1].startsWith('step 11') && EQC.it.t.rows.at(-3)[1].startsWith('passo 11') && EQC.en.t.rows.at(-3)[2].includes(`${C.rows} statements`), 'tally and navigation have the spin step');
ok(stepEyebrow('en', 'eq', 'spin') === `STEP 11 OF ${stepCount('eq')} · POINTORS AND THE THREE KINDS OF i` && stepEyebrow('it', 'eq', 'spin') === `PASSO 11 DI ${stepCount('eq')} · POINTOR E I TRE TIPI DI i`, 'eyebrow of the step');

// ---- 4. the live engine agrees with the exact script
for (const [k, v] of Object.entries(K.sp.planar)) { // the three kinds of i, from the exact table
  const [kind, , sig] = [k.split(',')[0], 0, JSON.parse(k.slice(k.indexOf('[') >= 0 ? k.indexOf('[') : k.length) || '[]')];
  if (kind === '1') ok(S.kinds(v.signature[0], 1).k1 === v.unit_square, `kind 1 ${k}`);
  else if (kind === '2') ok(S.kinds(v.signature[0], v.signature[1]).k2 === v.unit_square, `kind 2 ${k}`);
  else ok(S.kinds(v.signature[0], v.signature[1]).k3 === v.unit_square, `kind 3 ${k}`);
}
ok(S.kinds(0, 0).k3 === null && S.kinds(1, 1).k3 === -1 && S.kinds(1, -1).k3 === 1 && S.kinds(0, 1).k3 === 0, 'third kind: no reference vector, complex, split-complex, dual');
for (let d = 1; d <= 8; d++) { const p = S.pseudoscalar(d); ok(p.sq === ((d * (d - 1) / 2) % 2 ? -1 : 1) && p.central === (d % 2 === 1), `I^2 and centrality at d=${d}`); }
for (const [key, v] of Object.entries(K.sp.decomposition)) if (v.signature.every(x => x === 1)) { const L = S.labelling(v.d); ok(L.cls.size === v.classes && L.ok && L.sameAsPlus && L.selfDual, `labels d=${v.d}`); }
{ const L = S.labelling(6); ok([...L.cls.values()].every(b => b.length === 8) && L.H.length === 8 && L.ms.join() === '3,12,48', 'd=6: 8 classes of 8 blades, H of size 8, masks 3,12,48'); }
for (let n = 0; n <= 48; n++) { const r = S.planar(n * Math.PI / 12); ok(r.ok, `rotor at ${n * 15} degrees`); }
{ const a = S.planar(Math.PI), b = S.planar(2 * Math.PI); ok(Math.abs(a.R[0] + 1) < 1e-9 && Math.abs(a.vec[1] - 1) < 1e-9 && Math.abs(b.R[0] - 1) < 1e-9, 'R(pi) = -1 fixes the vector, R(2pi) = +1'); }
{ const P = S.spinors(3), E = P.E; let allOk = true;
  for (let i = 0; i < 8; i++) { const sg = [i & 1 ? -1 : 1, i & 2 ? -1 : 1, i & 4 ? -1 : 1], ph = P.phi(sg), iPhi = E.mul(P.I, ph);
    for (let j = 0; j < 3; j++) { const B = P.B(j); allOk &&= E.eq(E.mul(B, ph), E.scale(iPhi, sg[j])) && E.eq(E.mul(ph, B), iPhi) && E.eq(E.mul(E.mul(B, ph), E.inv(B)), E.scale(ph, sg[j])); } }
  ok(allOk, 'left, right and conjugation labels for all 8 orientations in Cl(7,0)');
  const a = 3 / 5, b = 4 / 5; let phOk = true;
  for (let s1 = 0; s1 < 8; s1++) for (let s2 = 0; s2 < 8; s2++) for (let j = 0; j < 3; j++) { const S1 = [s1 & 1 ? -1 : 1, s1 & 2 ? -1 : 1, s1 & 4 ? -1 : 1], S2 = [s2 & 1 ? -1 : 1, s2 & 2 ? -1 : 1, s2 & 4 ? -1 : 1]; const A = P.phi(S1), B2 = P.phi(S2), R = E.add(E.scale(E.one, a), E.scale(P.B(j), b)), M = E.add(A, E.scale(B2, 1.5)), RM = E.mul(R, M);
    const overall = E.eq(RM, E.mul(P.cx(a, b * S1[j]), M)); phOk &&= (overall === (S1[j] === S2[j] || E.eq(A, B2))) || s1 === s2; }
  ok(phOk, 'a rotation is an overall phase on a mixed state exactly when the planes agree'); }
{ const t = ['flatland', 'vR', 'unrelated', 'versor'].map(k => [...Array(12)].filter((_, i) => S.pointorSample(k, i + 1).ok).length);
  ok(t.join() === '12,12,0,12', 'pointor test: flatland, (a+bv)R and a rotor pass 12/12, an unrelated sum 0/12 (' + t + ')');
  const t3 = K.sp.theorem3; ok(Object.values(t3).every(x => x['(alpha+beta v)R'] === '6/6' && x['alpha R + beta P (P unrelated)'] === '0/6'), 'the exact file agrees with the widget on Theorem 3'); }
{ const agree = [...Array(24)].filter((_, i) => { const h = S.hestenes('generic', i + 1); return h.ok === (Math.abs(h.b) < 1e-9) && !h.other; }).length; ok(agree === 24, 'Hestenes: pointor exactly when b = 0 (' + agree + '/24)');
  ok([...Array(12)].every((_, i) => { const h = S.hestenes('versor', i + 1); return h.ok && Math.abs(h.b) < 1e-9; }), 'an even versor has b = 0');
  const ch = S.chirality(); ok(ch.length === 8 && ch.every(c => c.ok) && K.sp.chirality.xor === 9 && new Set(ch.map(c => Math.min(c.x, c.m))).size === 4, 'chirality is XOR 9 with four pairs'); }
{ const sp = S.spinors(1), E = sp.E, P = sp.phi([1]); let mixes = false, keeps = true;
  for (let n = 1; n <= 24; n++) { const th = n * Math.PI / 12, Rb = E.add(E.scale(E.one, Math.cos(th)), E.scale(sp.B(0), Math.sin(th))), Rw = E.add(E.scale(E.one, Math.cos(th)), E.scale(E.mul(sp.w, sp.v(0)), Math.sin(th)));
    const parity = X => { const wi = E.inv(sp.w), sw = E.mul(E.mul(sp.w, X), wi); return E.eq(sw, X); };
    keeps &&= parity(E.mul(Rb, P)); if (Math.abs(Math.sin(th) * Math.cos(th)) > 1e-9 || Math.abs(Math.sin(th)) > 1e-9) mixes ||= !parity(E.mul(Rw, P)); }
  ok(keeps && mixes, 'Spin(2) keeps the all-plus spinor in S+, the rotor with w mixes'); }
console.log(bad ? bad + ' FAILURES' : 'ALL SPIN TESTS PASS'); process.exit(bad ? 1 : 0);
