import React, { useRef, useState } from 'react';
import { Streamdown } from 'streamdown';
import { createMathPlugin } from '@streamdown/math';
import { BlockMath, InlineMath } from 'react-katex';
import SimplexCanvas from './SimplexCanvas';
import GenesisCanvas from './GenesisCanvas';
import FureyFindings from './FureyFindings';
import DictionarySection from './DictionarySection';
import MaxwellSection from './MaxwellSection';
import ThreeGenSection from './ThreeGenSection';
import ShapesSection from './ShapesSection';
import { StoryNav, PageIntro, StoryPager, usePage, STORY } from './StoryShell';
import { PROOFS, STATUS_LABEL, PROOF_UI } from './proofs';
import { KNOWLEDGE_BASE_DIRECTORY, MENU_SECTOR_LIST, GENESIS_STAGES, getCompleteDualMetricDisplayData, getGenesisDisplayData } from './matrixData';

const PROFILES=['Young Learner','Physicist','Mathematician'];
const VIEWS=['Clifford','Prime','Simplex','Cube'];
const CHAT_MATH = createMathPlugin({ singleDollarTextMath: true });
const CHAT_CONTROLS = { table: false, code: { copy: true, download: false }, mermaid: { copy: true, download: false, fullscreen: true, panZoom: true }, image: { download: false } };
const ChatResponse = ({content}) => <Streamdown plugins={{math: CHAT_MATH}} controls={CHAT_CONTROLS} remend={{katex:true}}>{content}</Streamdown>;
const LENSES={Clifford:['Minimal left ideals','Peirce projectors'],Prime:['Coprimality sieve','Arithmetic frequencies'],Simplex:['Combinatorial facets','Petrie graph edges'],Cube:['Boolean bit strings','Hamming distance vectors']};
const LENS_COPY={en:{'Young Learner':{Clifford:['Magic folding boxes','Hidden shape rules'],Prime:['Number gears','Secret timing counts'],Simplex:['Puzzle faces','Connecting paths'],Cube:['Switch addresses','Flip-distance steps']},Physicist:LENSES,Mathematician:LENSES},it:{'Young Learner':{Clifford:['Scatole magiche','Regole delle forme'],Prime:['Ingranaggi numerici','Conteggi segreti'],Simplex:['Facce del puzzle','Percorsi connessi'],Cube:['Indirizzi degli interruttori','Passi di ribaltamento']},Physicist:{Clifford:['Ideali sinistri minimi','Proiettori di Peirce'],Prime:['Setaccio di coprimalità','Frequenze aritmetiche'],Simplex:['Facce combinatorie','Bordi del grafo Petrie'],Cube:['Stringhe di bit booleane','Vettori di distanza di Hamming']},Mathematician:{Clifford:['Ideali sinistri minimi','Proiettori di Peirce'],Prime:['Setaccio di coprimalità','Frequenze aritmetiche'],Simplex:['Facce combinatorie','Bordi del grafo Petrie'],Cube:['Stringhe di bit booleane','Vettori di distanza di Hamming']}}};
const labels={en:{tour:'The shared four-step tour',results:'Three result branches',matrix:'Language · audience · representation',note:'Educational visual toy model — not an established peer-reviewed physical theory.',lede:'A structured visual translation atlas for tracing one combinatorial toy model across geometric algebra, arithmetic, simplex topology, and Boolean coordinates.',open:'Open branch',step:'Step',active:'Active sector',activeNote:'Choose any atlas node below. Its detailed explanation and visualization stay here, directly after the lattice.',now:'Now exploring',directory:'Sector directory',viewing:'Viewing',viewNode:'View',atlas:'Visual semantic translation atlas',hero:'Space as language, not a container.',base:'Base / Right action',baseDesc:'Macroscopic coordinates',fiber:'Fiber / Left action',fiberDesc:'Internal phase clocks',turntable:'The four-view translation turntable',turntableTitle:'One cell, four synchronized lenses.',lattice:'Immutable 2D lattice grid',latticeTitle:'Navigate by B+F / B−F coordinate.',research:'Research',activeVisual:'Active sector visualization',supporting:'Supporting learning module'},it:{tour:'Il tour condiviso in quattro passi',results:'Tre rami di risultati',matrix:'Lingua · pubblico · rappresentazione',note:'Modello visivo educativo — non una teoria fisica consolidata e sottoposta a peer review.',lede:'Un atlante visivo strutturato per tracciare un modello combinatorio attraverso algebra geometrica, aritmetica, topologia del simplesso e coordinate booleane.',open:'Apri il ramo',step:'Passo',active:'Settore attivo',activeNote:'Scegli un nodo dell’atlante qui sotto. La spiegazione dettagliata e la visualizzazione rimangono qui, subito dopo il reticolo.',now:'In esplorazione',directory:'Elenco dei settori',viewing:'In visione',viewNode:'Apri',atlas:'Atlante di traduzione semantica visiva',hero:'Lo spazio come linguaggio, non come contenitore.',base:'Base / Azione destra',baseDesc:'Coordinate macroscopiche',fiber:'Fibra / Azione sinistra',fiberDesc:'Orologi di fase interni',turntable:'Tavola rotante di traduzione a quattro viste',turntableTitle:'Una cella, quattro lenti sincronizzate.',lattice:'Reticolo 2D immutabile',latticeTitle:'Naviga tramite coordinate B+F / B−F.',research:'Ricerca',activeVisual:'Visualizzazione del settore attivo',supporting:'Modulo di apprendimento di supporto'}};
const ATLAS_COPY={
 en:{
  'Young Learner':{atlas:'Magic switch atlas',hero:'A story where time and space take turns.',lede:'Explore eight magic switches, sandbox paths, secret clock gears, and mirror gates.',turntable:'Four magic views',turntableTitle:'One puzzle, four ways to see it.',lattice:'Switch map',latticeTitle:'Choose a place in the magic grid.',active:'Active magic place',activeNote:'Pick any atlas place. Its story and picture appear here.',supporting:'Story adventure'},
  Physicist:{atlas:'Visual semantic translation atlas',hero:'Space as language, not a container.',lede:'A structured visual translation atlas for tracing a combinatorial toy model across gauge geometry, arithmetic, simplex topology, and Boolean coordinates.',turntable:'The four-view translation turntable',turntableTitle:'One cell, four synchronized lenses.',lattice:'Immutable 2D lattice grid',latticeTitle:'Navigate by B+F / B−F coordinate.',active:'Active sector',activeNote:'Choose any atlas node. Its detailed explanation and visualization stay here, directly after the lattice.',supporting:'Supporting learning module'},
  Mathematician:{atlas:'Bigraded Clifford translation atlas',hero:'One algebra, multiple coordinate languages.',lede:'A cross-talk atlas of ideals, filtrations, combinatorial facets, and Boolean involutions over a two-dimensional lattice.',turntable:'Four-representation functorial turntable',turntableTitle:'One lattice cell, four compatible projections.',lattice:'Bigraded 2D lattice',latticeTitle:'Select a cell by B+F and B−F grading.',active:'Active algebraic cell',activeNote:'Choose a lattice cell. Its proposition and geometric projection appear here.',supporting:'Supporting construction sequence'}
 },
 it:{
  'Young Learner':{atlas:'Atlante degli interruttori magici',hero:'Una storia dove tempo e spazio si alternano.',lede:'Esplora otto interruttori magici, percorsi nel recinto, ingranaggi-orologio segreti e cancelli a specchio.',turntable:'Quattro viste magiche',turntableTitle:'Un puzzle, quattro modi di guardarlo.',lattice:'Mappa degli interruttori',latticeTitle:'Scegli un posto nella griglia magica.',active:'Luogo magico attivo',activeNote:'Scegli un luogo dell’atlante. La sua storia e la sua immagine appaiono qui.',supporting:'Avventura narrativa'},
  Physicist:{atlas:'Atlante di traduzione semantica visiva',hero:'Lo spazio come linguaggio, non come contenitore.',lede:'Un atlante visivo strutturato per tracciare un modello combinatorio attraverso geometria di gauge, aritmetica, topologia del simplesso e coordinate booleane.',turntable:'Tavola rotante di traduzione a quattro viste',turntableTitle:'Una cella, quattro lenti sincronizzate.',lattice:'Reticolo 2D immutabile',latticeTitle:'Naviga tramite coordinate B+F / B−F.',active:'Settore attivo',activeNote:'Scegli un nodo dell’atlante. La spiegazione dettagliata e la visualizzazione rimangono qui.',supporting:'Modulo di apprendimento di supporto'},
  Mathematician:{atlas:'Atlante di traduzione Clifford bigradato',hero:'Una algebra, molte lingue di coordinate.',lede:'Un atlante di cross-talk tra ideali, filtrazioni, facce combinatorie e involuzioni booleane su un reticolo bidimensionale.',turntable:'Tavola funttoriale a quattro rappresentazioni',turntableTitle:'Una cella del reticolo, quattro proiezioni compatibili.',lattice:'Reticolo 2D bigradato',latticeTitle:'Seleziona una cella tramite la gradazione B+F e B−F.',active:'Cella algebrica attiva',activeNote:'Scegli una cella del reticolo. La sua proposizione e proiezione geometrica appaiono qui.',supporting:'Sequenza costruttiva di supporto'}
 }
};
const HERO_BANNER_HOOKS={
 Spatial:{
  en:{'Young Learner':['The Great Sandbox Builder','Click switches and fold magic boxes to build a universe out of block sandboxes.'],Physicist:['Projective Manifold Atlas','A geometric gauge translation engine tracking bivector curvatures over flat space-positive backgrounds.'],Mathematician:['Cl(4,4,0) Invariant Directory','Systematic classification of principal left-ideals, minimal algebra representations, and Witt splits.']},
  it:{'Young Learner':['Il Grande Costruttore del Recinto','Attiva gli interruttori e piega scatole magiche per costruire un universo di sabbia.'],Physicist:['Atlante della Varietà Proiettiva','Un motore di traduzione di gauge geometrico che traccia curvature bivettoriali su sfondi piatti a spazio positivo.'],Mathematician:['Elenco degli Invarianti di Cl(4,4,0)','Classificazione sistematica degli ideali sinistri principali, delle rappresentazioni algebriche minime e degli split di Witt.']}
 },
 Temporal:{
  en:{'Young Learner':['The Infinite Movie Projector','Time as chronicle, space as constraint. Watch the rolling film reel unspool across internal gears.'],Physicist:['Chronological Displacement Field','A kinematic reading where space, mass, and charge are topological ripples of chronology foregrounded over a time-positive lattice.'],Mathematician:['Temporal Bimodule Operator Chain','Mapping regular hypercomplex transformations and regular representation actions over self-dual temporal modules.']},
  it:{'Young Learner':['Il Proiettore del Film Infinito','Il tempo come cronaca, lo spazio come vincolo. Guarda la pellicola scorrere sugli ingranaggi interni.'],Physicist:['Campo di Spostamento Cronologico','Una lettura cinematica in cui spazio, massa e carica sono increspature topologiche di una cronologia posta in primo piano.'],Mathematician:['Catena dell’Operatore Bimodulo Temporale','Mappatura delle trasformazioni ipercomplesse regolari e delle azioni di rappresentazione su moduli temporali auto-duali.']}
 }
};
function getAtlasCopy(lang,profile,metricMode){const base=ATLAS_COPY[lang][profile];const S=STORY[lang]||STORY.en;const [hero,lede]=S.hero[profile];const [metric,metricNote]=S.metric[metricMode];return {...base,hero,lede,metric,metricNote};}

export default function App(){
 const [lang,setLang]=useState('en'),[profile,setProfile]=useState('Young Learner'),[metricMode,setMetricMode]=useState('Spatial'),[view,setView]=useState('Clifford'),[genesisStep,setGenesisStep]=useState(0),[sector,setSector]=useState('Sector_EM_Maxwell');
 const resultRef = useRef(null);
 const t=labels[lang], c=getAtlasCopy(lang,profile,metricMode), record=getCompleteDualMetricDisplayData(sector,lang,profile,metricMode), genesis=getGenesisDisplayData(genesisStep,lang,profile,metricMode), selected=MENU_SECTOR_LIST.find(x=>x.id===sector);
 const [page,setPage]=usePage();
 const intro=<PageIntro lang={lang} page={page}/>, pager=<StoryPager lang={lang} page={page} setPage={setPage}/>;
 return <main>
  <StoryNav lang={lang} page={page} setPage={setPage}/>
  <ControlBar lang={lang} setLang={setLang} profile={profile} setProfile={setProfile} metricMode={metricMode} setMetricMode={setMetricMode} view={view} setView={setView}/>
  {page==='rule'&&<><section className="atlas-hero" id="top"><p className="eyebrow">{c.atlas.toUpperCase()}</p><h1>{c.hero}</h1><p className="lede">{c.lede}</p><p className="metric-readout">{c.metric} · {c.metricNote}</p><div className="action-model"><span><b>{t.base}</b>{t.baseDesc}</span><i>⊗</i><span><b>{t.fiber}</b>{t.fiberDesc}</span></div><p className="disclosure">{(STORY[lang]||STORY.en).note}</p></section>{intro}<Turntable c={c} lang={lang} profile={profile} view={view} setView={setView}/><GenesisAdventure t={t} c={c} step={genesisStep} setStep={setGenesisStep} profile={profile} view={view} record={genesis} metricMode={metricMode} lang={lang}/></>}
  {page==='atlas'&&<>{intro}<LatticeMap c={c} sector={sector} setSector={setSector} lang={lang} profile={profile} metricMode={metricMode} resultRef={resultRef}/><section className="explorer-intro"><p className="eyebrow">{c.active.toUpperCase()}</p><h2>{c.active}</h2><p>{c.activeNote}</p></section><section className="result active-result" ref={resultRef} tabIndex="-1"><article className="paper"><p className="eyebrow">{t.now.toUpperCase()} · {selected.category.toUpperCase()} · {view.toUpperCase()} VIEW</p><h2>{record.title}</h2>{record.subtitle&&<p className="subtitle">{record.subtitle}</p>}{record.auditStatus&&(()=>{const S=STORY[lang]||STORY.en,k=record.auditStatus==='speculative'?'open':'checked',lab={verified:lang==='it'?'cella verificata':'cell verified',realigned:lang==='it'?'cella riallineata dopo l’audit':'cell realigned by the audit',speculative:lang==='it'?'lettura speculativa':'speculative reading'}[record.auditStatus];return <p className="audit-line"><span className={'tag '+k} title={S.tagHelp[k]}>{S.tags[k]} · {lab}</span> {record.auditedCell}</p>})()}<p>{record.desc}</p><ResultFormal sector={sector} profile={profile} lang={lang} record={record}/></article><aside className="proof-map"><p className="eyebrow">{t.activeVisual.toUpperCase()}</p><SimplexCanvas step={3} activeView={view} sector={sector} metricMode={metricMode} lang={lang}/><div className="view-pills">{VIEWS.map(v=><button onClick={()=>setView(v)} className={v===view?'active':''} key={v}>{v}: {telemetry(record,v)}</button>)}</div></aside></section><SectorNavigator lang={lang} profile={profile} metricMode={metricMode} t={t} sector={sector} setSector={setSector} resultRef={resultRef}/></>}
  {page==='maxwell'&&<>{intro}<MaxwellSection lang={lang} profile={profile}/></>}
  {page==='furey'&&<>{intro}<DictionarySection lang={lang} profile={profile}/><ThreeGenSection lang={lang} profile={profile}/><FureyFindings lang={lang} profile={profile}/></>}
  {page==='shapes'&&<>{intro}<ShapesSection lang={lang} profile={profile}/></>}
  {page==='ask'&&<>{intro}<ChatPanel lang={lang} profile={profile} metricMode={metricMode}/></>}
  {pager}
  <footer><span>Clifford · Prime · Simplex · Cube</span><span>{(STORY[lang]||STORY.en).note}</span></footer>
 </main>
}
function Turntable({c,lang,profile,view,setView}){const lensCopy=LENS_COPY[lang][profile];return <section className="turntable"><p className="eyebrow">{c.turntable.toUpperCase()}</p><h2>{c.turntableTitle}</h2><div className="lens-grid">{VIEWS.map(v=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}><b>{v} lens</b><span>{lensCopy[v][0]}</span><span>{lensCopy[v][1]}</span></button>)}</div></section>}
function LatticeMap({c,sector,setSector,lang,profile,metricMode,resultRef}){const rows=MENU_SECTOR_LIST.reduce((all,item)=>{const record=getCompleteDualMetricDisplayData(item.id,lang,profile,metricMode);const row=(record.coordinate.match(/B\+F=(\d+)/)||[])[1]||'Research';(all[row]??=[]).push(item);return all;},{});return <section className="lattice-map"><p className="eyebrow">{c.lattice.toUpperCase()}</p><h2>{c.latticeTitle}</h2><div className="lattice-rows">{Object.entries(rows).sort(([a],[b])=>Number(a)-Number(b)).map(([row,items])=><div className="lattice-row" key={row}><small>{row==='Research'?'RESEARCH':`ROW ${row}`}</small><div>{items.map(item=>{const r=getCompleteDualMetricDisplayData(item.id,lang,profile,metricMode);const active=sector===item.id;return <button className={active?'active':''} onClick={()=>{setSector(item.id);requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}} key={item.id}><span>{r.coordinate.split(',').at(-1).trim()}</span><b>{r.title}</b></button>})}</div></div>)}</div></section>}
function GenesisAdventure({t,c,step,setStep,profile,view,record,metricMode,lang}){return <section className="tour-block genesis-adventure"><p className="eyebrow">{c.supporting.toUpperCase()} · {t.tour.toUpperCase()}</p><div className="tour"><div className="tour-copy"><p className="eyebrow">GENESIS {String(step).padStart(2,'0')} / 08 · {profile.toUpperCase()}</p><h2>{record.title}</h2><p>{record.desc}</p><p className="cue">{record.coordinate} · {view} lens</p><div className="steps">{GENESIS_STAGES.map((id,index)=><button onClick={()=>setStep(index)} className={index===step?'active':''} key={id}>{String(index).padStart(2,'0')}</button>)}</div></div><div className="diagram"><GenesisCanvas stage={step} metricMode={metricMode} profile={profile} lang={lang}/><span>Genesis stage {step}: {record.grade}</span></div></div></section>}

function SectorNavigator({lang,profile,metricMode,t,sector,setSector,resultRef}){const groups=MENU_SECTOR_LIST.reduce((all,item)=>{(all[item.category]??=[]).push(item);return all;},{});return <section className="sector-navigator"><p className="eyebrow">{t.directory.toUpperCase()} · {MENU_SECTOR_LIST.length} NODES</p><div className="sector-groups">{Object.entries(groups).map(([category,items])=><div className="sector-group" key={category}><h3>{category}</h3>{items.map(item=>{const data=getCompleteDualMetricDisplayData(item.id,lang,profile,metricMode);const active=item.id===sector;return <button className={active?'active':''} aria-pressed={active} onClick={()=>{setSector(item.id);requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}} key={item.id}><span>{data.title}</span><small>{active?t.viewing:t.viewNode}</small></button>})}</div>)}</div></section>}
function ControlBar({lang,setLang,profile,setProfile,metricMode,setMetricMode,view,setView}){return <section className="controls" aria-label="Presentation controls"><div className="control-title"><span>Presentation matrix</span><small>{lang.toUpperCase()} · {profile} · {view}</small></div><div className="control-group language-group"><p>LANGUAGE</p><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button><button className={lang==='it'?'active':''} onClick={()=>setLang('it')}>IT</button></div><div className="control-group audience-group"><p>AUDIENCE</p>{PROFILES.map(x=><button className={profile===x?'active':''} onClick={()=>setProfile(x)} key={x}>{x==='Young Learner'?'Learner':x==='Physicist'?'Physics':'Math'}</button>)}</div><div className="control-group metric-group"><p>METRIC</p><button className={metricMode==='Spatial'?'active':''} onClick={()=>setMetricMode('Spatial')}>Space +</button><button className={metricMode==='Temporal'?'active':''} onClick={()=>setMetricMode('Temporal')}>Time +</button></div><div className="control-group lens-group"><p>LENS</p>{VIEWS.map(x=><button className={view===x?'active':''} onClick={()=>setView(x)} key={x}>{x}</button>)}</div></section>}
function telemetry(record,view){return view==='Clifford'?record.grade:view==='Prime'?`Multiplicity [${record.coordinate}]`:view==='Simplex'?record.simplex:record.cube}
function ResultFormal({ sector, profile, lang }) {
 if (profile === 'Young Learner') return null;
 const L = lang === 'it' ? 'it' : 'en', entry = PROOFS[sector], ui = PROOF_UI[L];
 if (!entry) return <details className="formal-proof"><summary>{ui.open}</summary><div className="theorem"><p>{ui.missing}</p></div></details>;
 const item = entry[L], badge = { derived: '#34d399', interpretive: '#fbbf24', open: '#f87171' }[entry.status];
 return <details className="formal-proof"><summary>{ui.open}</summary><div className="theorem">
  <b>{item.title}</b>
  <p className="proof-status" style={{display:'inline-block',margin:'6px 0',padding:'2px 8px',borderRadius:6,border:`1px solid ${badge}`,color:badge,fontSize:'.8em'}}>{STATUS_LABEL[L][entry.status]}</p>
  <p>{item.statement}</p>
  <BlockMath math={item.eq}/>
  <p><b>{ui.sketch}.</b> {item.proof}</p>
  <div className="lemma"><b>{item.lemmaTitle}</b><BlockMath math={item.lemmaEq}/></div>
  {item.caveat&&<p className="proof-caveat" style={{borderLeft:'3px solid '+badge,paddingLeft:10,opacity:.9}}><b>{ui.caveat}.</b> {item.caveat}</p>}
 </div></details>;
}

function ChatPanel({lang,profile,metricMode}) {
 const [input,setInput]=useState('');
 const [agent,setAgent]=useState('anthropic');
 const [answer,setAnswer]=useState('');
 const [outputs,setOutputs]=useState({anthropic:'',openai:''});
 const [loading,setLoading]=useState(false);
 const [matchRunning,setMatchRunning]=useState(false);
 const unavailable=lang==='it'?'Il servizio chat non è disponibile.':'Chat is unavailable.';
 async function readStream(url, payload, onText, onStatus) {
  const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});
  if(!response.ok||!response.body) throw new Error('unavailable');
  const reader=response.body.getReader(),decoder=new TextDecoder(); let text='',buffer='';
  while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=done?'':lines.pop();for(const line of lines){if(!line.startsWith('data: ')||line.includes('[DONE]'))continue;try{const event=JSON.parse(line.slice(6));if(event.type==='status'){onStatus?.(event.message);continue}if(event.type==='error')throw new Error(event.message||'unavailable');const delta=event.type==='content_block_delta'?event.delta?.text||'':event.choices?.[0]?.delta?.content||'';if(delta){text+=delta;onText(text)}}catch{}}if(done)break}
 }
 const payload=()=>({spokenLang:lang,userProfile:profile,metricMode,messages:[{role:'user',content:input}]});
 async function ask(e){e.preventDefault();if(!input.trim()||loading)return;setLoading(true);setAnswer('');try{await readStream(agent==='openai'?'/api/chat-openai':'/api/chat',payload(),setAnswer,status=>setAnswer(status))}catch{setAnswer(unavailable)}finally{setLoading(false)}}
 async function runCoreMatch(){if(!input.trim()||matchRunning)return;setMatchRunning(true);setOutputs({anthropic:'',openai:''});const matchPayload={...payload(),isMatchMode:true};await Promise.allSettled([readStream('/api/chat',matchPayload,text=>setOutputs(current=>({...current,anthropic:text}))),readStream('/api/chat-openai',matchPayload,text=>setOutputs(current=>({...current,openai:text})),status=>setOutputs(current=>({...current,openai:status})))]).then(results=>results.forEach((result,index)=>{if(result.status==='rejected')setOutputs(current=>({...current,[index?'openai':'anthropic']:unavailable}))}));setMatchRunning(false)}
 return <section className={`chat ${outputs.anthropic||outputs.openai?'chat-has-match':''}`}><p className="eyebrow">CASCADE GUIDE · {profile.toUpperCase()} · {metricMode==='Temporal'?'TIME+':'SPACE+'}</p><h2>{lang==='it'?'Chiedi al modello':'Ask the model'}</h2><div className="agent-selector" role="group" aria-label="Chat agent"><button type="button" className={agent==='anthropic'?'active anthropic-agent':''} onClick={()=>setAgent('anthropic')}>Claude Opus</button><button type="button" className={agent==='openai'?'active openai-agent':''} onClick={()=>setAgent('openai')}>OpenAI o3</button></div><form className="chat-composer" onSubmit={ask}><textarea value={input} onChange={e=>setInput(e.target.value)} onInput={e=>{e.currentTarget.style.height='auto';e.currentTarget.style.height=`${Math.min(e.currentTarget.scrollHeight,280)}px`}} placeholder={lang==='it'?'Fai una domanda':'Ask a question'} maxLength="4000" rows="2"/><div className="chat-actions"><button className="ask-button" disabled={loading||matchRunning}>{loading?'…':lang==='it'?'Invia':'Ask'}</button><button className="match-button" type="button" disabled={!input.trim()||loading||matchRunning} onClick={runCoreMatch}>{matchRunning?(lang==='it'?'Confronto in corso…':'Comparing…'):(lang==='it'?'Confronta modelli':'Compare models')}</button></div></form>{answer&&<article className="answer markdown-response"><ChatResponse content={answer}/></article>}{(outputs.anthropic||outputs.openai)&&<div className="match-arena"><article className="agent-column anthropic-border"><p className="eyebrow">ANTHROPIC · CLAUDE OPUS</p>{outputs.anthropic?<ChatResponse content={outputs.anthropic}/>:<span>…</span>}</article><article className="agent-column openai-border"><p className="eyebrow">OPENAI · O3</p>{outputs.openai?<ChatResponse content={outputs.openai}/>:<span>…</span>}</article></div>}</section>}
