"""Does a family structure carry a 3?  Tests the two candidates left open by threegen_selfcheck.py in the explicit 16-dim model of run_all.py:
 (A) the Witt torus: 16 joint eigenspaces ('axes') of the commuting Fano-line blades, a (Z2)^4 grading of End(V) = M16(R);
 (B) the Z2 parallel: a second complex structure omega' = -R_{e7} compatible with the same Peirce blocks.
Run: python3 family_test.py  -> asserts everything and writes family_results.json"""
import sys, json, itertools; sys.path.insert(0, '.')
import numpy as np
from model import *
res = {}
com = lambda A, B: A @ B - B @ A
tr = lambda M: int(round(np.trace(M)))
k = E[3]; Lk, Rk = Lmat(k), Rmat(k); LR = Lk @ Rk
PO1, PO2 = (I8 - LR) / 2, (I8 + LR) / 2
def proj(P8, second):
    P = np.zeros((16, 16)); P[:8, :8] = P8
    for m in second: P[8 + m, 8 + m] = 1
    return P
real = [proj(PO1, ()), proj(PO2, ()), proj(0 * I8, (4, 5, 6, 7)), proj(0 * I8, (1, 2)), proj(0 * I8, (3,)), proj(0 * I8, (0,))]
names = ['O1', 'O2', 'H', 'C', 'e7R', 'R']
om = diag2(Lk); om2 = diag2(-Rk)
Q = [real[0], real[1], real[2], real[3], real[4] + real[5]]               # complex blocks (omega swaps the last two real ones)
cn = ['C_O(1)', 'C3_O(3)', 'C2_H(2)', 'C_C(1)', 'C_last(1)']
ranks = [tr(q) // 2 for q in Q]; assert ranks == [1, 3, 2, 1, 1]
def nullspace_commuting(gens, n=16, tol=1e-9):
    # incremental: keep an orthonormal basis N of the matrices commuting with every generator seen so far (vec in column-major order)
    N = np.eye(n * n)
    for g in gens:
        A = (np.kron(np.eye(n), g) - np.kron(g.T, np.eye(n))) @ N
        u, s, vt = np.linalg.svd(A, full_matrices=True)
        r = int(np.sum(s > tol)); N = N @ vt[r:].T
        if N.shape[1] == 0: break
    return [N[:, c].reshape(n, n, order='F') for c in range(N.shape[1])]
def rank(Ms): return int(np.linalg.matrix_rank(np.array([M.reshape(-1) for M in Ms]), tol=1e-9)) if Ms else 0
def span_dim(Ms): return rank(Ms)
# ---------------- the gauge algebra Delta_SM (real dimension 31): omega-linear maps inside each complex block, only the reals on the last block
L_om = nullspace_commuting([om])                                             # omega-linear operators, 128 real dimensions
assert len(L_om) == 128
delta = []
for i in range(4):
    for X in L_om:
        Y = Q[i] @ X @ Q[i]
        if np.linalg.norm(Y) > 1e-9: delta.append(Y)
delta.append(Q[4])
def indep(Ms):
    out = []
    for M in Ms:
        if rank(out + [M]) > len(out): out.append(M)
    return out
delta_basis = indep(delta)
dD = rank(delta_basis); assert dD == 31, dD
res['delta_SM_real_dim'] = dD
# ---------------- 1. what commutes with the gauge algebra (a family symmetry that keeps Standard Model quantum numbers must live here)
cent = nullspace_commuting(delta_basis[:])                                    # commutant of Delta_SM in End_R(V)
res['commutant_of_gauge_real_dim'] = len(cent)
# structure: it is block-diagonal; per block the commutant of the block algebra
per_block = []
for i in range(5):
    Ci = [Q[i] @ X @ Q[i] for X in cent]; per_block.append(rank(Ci))
res['commutant_per_block_real_dim'] = dict(zip(cn, per_block))
off = rank([Q[a] @ X @ Q[b] for X in cent for a in range(5) for b in range(5) if a != b])
res['commutant_off_block_real_dim'] = off
assert off == 0 and per_block == [2, 2, 2, 2, 4] and len(cent) == 12, (off, per_block, len(cent))
# => a gauge-commuting symmetry acts on each Peirce block only through scalars (complex phases), and on the last block through GL2(R).
# the multiplicity of Q_L in End(V) is 1 (threegen_selfcheck.py), so such a symmetry multiplies Q_L by a single number: it cannot carry a 3.
# ---------------- 2. witt torus
units = [E[m] for m in range(1, 8)]
g = [blk(Z, Lmat(u), Lmat(u), Z) for u in units] + [blk(Z, I8, -I8, Z)]
lines = []
for a in range(7):
    for b in range(a + 1, 7):
        p = omul(units[a], units[b]); c = int(np.argmax(abs(p))) - 1
        if c > b: lines.append((a, b, c))
def blade(S):
    M = I16.copy()
    for a in S: M = M @ g[a]
    return M
A = [blade(l + (7,)) for l in lines]; assert len(lines) == 7
lab = [tuple(int(round((1 - np.diag(a)[i]) / 2)) for a in A) for i in range(16)]
# GF(2) rank of the labels -> 4 independent bits
def gf2_basis(vs):
    basis = []  # list of (pivot, vector) in reduced form
    for v in vs:
        v = list(v)
        for piv, b in basis:
            if v[piv]: v = [x ^ y for x, y in zip(v, b)]
        if any(v): basis.append((next(i for i, x in enumerate(v) if x), v))
    return [b for _, b in basis]
lab_s = [tuple(x ^ y for x, y in zip(l, lab[0])) for l in lab]   # the 16 labels form an affine 4-space (no zero label): shift by one of them
assert len(gf2_basis(lab_s)) == 4
# the torus group generated by the line blades (as diagonal sign matrices)
tor = {tuple(np.diag(np.eye(16)).astype(int))}
mats = [np.diag(a) for a in A]; group = {tuple(np.ones(16, dtype=int))}
for m in mats:
    group |= {tuple((np.array(x) * m).astype(int)) for x in group}
assert len(group) == 32   # {+1,-1} x (Z2)^4: the seven blade sign-vectors are the affine functions on the 16 axes
res['torus_group_order'] = len(group)
T = [np.diag(np.array(x, dtype=float)) for x in sorted(group)]
# (2a) which torus elements commute with the whole gauge algebra, and which lie in it
comm_gauge = [t for t in T if all(np.allclose(com(t, d), 0) for d in delta_basis)]
in_gauge = [t for t in T if rank(delta_basis + [t]) == dD]
res['torus_elements_commuting_with_gauge'] = len(comm_gauge)
res['torus_elements_inside_gauge_algebra'] = len(in_gauge)
# (2b) the torus grades End(V): degree of E_ab = lab[a] xor lab[b]; each degree has 16 matrix units
deg = lambda a, b: tuple(x ^ y for x, y in zip(lab[a], lab[b]))
degs = sorted({deg(a, b) for a in range(16) for b in range(16)}); res['torus_degrees'] = len(degs); assert len(degs) == 16
# axes in each real block
block_axes = {n: [i for i in range(16) if abs(real[j][i, i] - 1) < 1e-9] for j, n in enumerate(names)}
res['block_axes'] = block_axes
# omega and the grading: does omega have a single degree?
def degree_of(M):
    S = {deg(a, b) for a in range(16) for b in range(16) if abs(M[a, b]) > 1e-9}; return sorted(S)
res['omega_degrees'] = degree_of(om); res['omega_prime_degrees'] = degree_of(om2)
# (2c) the degrees occupied by each Peirce edge of the linear sector, and by one generation
edges = {}
Lbasis = L_om
for a in range(5):
    for b in range(5):
        if a == b: continue
        sp = [Q[b] @ X @ Q[a] for X in Lbasis]; sp = [M for M in sp if np.linalg.norm(M) > 1e-9]
        edges[(a, b)] = sp
        assert rank(sp) == 2 * ranks[a] * ranks[b]
# degrees of a matrix: set of degrees its support touches; an edge space is graded iff it is a direct sum of its degree parts
def graded_pieces(sp):
    # project each basis element on each degree and count dimension of every degree part of the space
    pieces = {}
    for d in degs:
        mask = np.zeros((16, 16))
        for a_ in range(16):
            for b_ in range(16):
                if deg(a_, b_) == d: mask[a_, b_] = 1
        part = [M * mask for M in sp]; part = [M for M in part if np.linalg.norm(M) > 1e-9]
        pieces[d] = rank(part)
    return pieces
sm_edges = {'Q_L': (1, 2), 'u_R': (1, 3), 'd_R': (1, 4), 'L': (3, 2), 'e_R': (3, 4), 'nu_R': (0, 4)}       # (source, target) as in run_all.py
res['sm_edge_degree_dimensions'] = {}
graded_ok = {}
for nme, (s, t) in sm_edges.items():
    sp = edges[(s, t)]; pcs = graded_pieces(sp)
    graded_ok[nme] = (sum(pcs.values()) == rank(sp))
    res['sm_edge_degree_dimensions'][nme] = {''.join(map(str, d)): v for d, v in pcs.items() if v}
res['sm_edges_are_graded_subspaces'] = graded_ok
# number of distinct degrees touched by the whole generation
used = sorted({d for nme in sm_edges for d, v in graded_pieces(edges[sm_edges[nme]]).items() if v})
res['degrees_touched_by_one_generation'] = len(used)
# ---- (2d) symmetries of the torus frame: affine maps of the 16 axes (as AG(4,2)) that preserve the block partition
L4 = np.array(gf2_basis(lab_s))                                                 # 4 x 7 basis of the label space
def coords(lbl):
    # solve lbl = sum c_i basis_i over GF(2) by brute force
    for c in itertools.product((0, 1), repeat=4):
        v = [0] * 7
        for ci, b in zip(c, L4):
            if ci: v = [x ^ y for x, y in zip(v, b)]
        if tuple(v) == tuple(lbl): return c
    raise ValueError
C4 = [coords(l) for l in lab_s]; assert len(set(C4)) == 16
idx = {c: i for i, c in enumerate(C4)}
vecs = list(itertools.product((0, 1), repeat=4))
def mat_inv_ok(M):
    # invertible over GF(2)?
    rows = [int(''.join(map(str, r)), 2) for r in M]; basis = []
    for r in rows:
        for b in basis: r = min(r, r ^ b)
        if r: basis.append(r)
    return len(basis) == 4
blocksets = [frozenset(block_axes[n]) for n in names]
cx = {}
G = []
for flat in itertools.product((0, 1), repeat=16):
    M = [flat[0:4], flat[4:8], flat[8:12], flat[12:16]]
    if not mat_inv_ok(M): continue
    for tvec in vecs:
        perm = []
        for c in C4:
            y = tuple((sum(M[r][j] * c[j] for j in range(4)) + tvec[r]) % 2 for r in range(4)); perm.append(idx[y])
        if all(frozenset(perm[i] for i in bs) == bs for bs in blocksets): G.append(tuple(perm))
G = sorted(set(G)); res['frame_symmetries_preserving_blocks'] = len(G)
def order(p):
    q = list(range(16)); n = 0
    while True:
        q = [p[i] for i in q]; n += 1
        if q == list(range(16)): return n
orders = {}
for p in G: orders[order(p)] = orders.get(order(p), 0) + 1
res['order_histogram'] = {str(k): v for k, v in sorted(orders.items())}
# order-3 elements: how do they act?
three = [p for p in G if order(p) == 3]
acts = set()
for p in three:
    cyc = []
    seen = set()
    for i in range(16):
        if i in seen: continue
        c = [i]; j = p[i]
        while j != i: c.append(j); j = p[j]
        seen |= set(c)
        if len(c) > 1: cyc.append(tuple(sorted(c)))
    blocks_touched = sorted({names[[j for j, bs in enumerate(blocksets) if c[0] in bs][0]] for c in cyc})
    acts.add(tuple(blocks_touched))
res['order3_elements'] = len(three); res['order3_blocks_touched'] = [list(a) for a in sorted(acts)]
# does each order-3 axis permutation commute with omega (up to sign) and lie in the gauge group?
def permmat(p):
    P = np.zeros((16, 16))
    for i, j in enumerate(p): P[j, i] = 1
    return P
inside = []
for p in three:
    P = permmat(p)
    inside.append({'commutes_with_omega': bool(np.allclose(com(P, om), 0)), 'anticommutes_with_omega': bool(np.allclose(P @ om + om @ P, 0)), 'permutes_axes_inside_blocks_only': True})
res['order3_commute_with_omega'] = sum(1 for d in inside if d['commutes_with_omega'])
# ---------------- 3. the Z2 parallel: complex structures compatible with the same Peirce blocks
D = np.linalg.solve(om, om2); dd = np.diag(D); assert np.allclose(D, np.diag(dd))
res['omega_prime_over_omega_minus_axes'] = [int(i) for i in np.nonzero(dd < 0)[0]]
# all J = omega * t with t a torus element (+/-): J^2 = -1 and J commutes with the five complex-block projectors and swaps the last two real blocks
cands = []
for t in T:
    for s in (1, -1):
        Jc = s * om @ t
        if np.allclose(Jc @ Jc, -I16) and all(np.allclose(com(Jc, q), 0) for q in Q):
            cands.append((s, t, Jc))
distinct = []
for s, t, Jc in cands:
    if not any(np.allclose(Jc, J2) or np.allclose(Jc, -J2) for J2 in distinct): distinct.append(Jc)
res['complex_structures_omega_times_torus'] = len(distinct)
# in the whole blade basis: every blade J with J^2=-1 commuting with the five complex-block projectors
subsets = [S for r in range(9) for S in itertools.combinations(range(8), r)]
blades_J = []
for S in subsets:
    M = blade(S)
    if np.allclose(M @ M, -I16) and all(np.allclose(com(M, q), 0) for q in Q): blades_J.append(S)
res['blade_complex_structures_commuting_with_blocks'] = len(blades_J)
# which of them swap the last two real blocks (so that the last complex block has rank 1 like omega)
def swaps_last(J):
    return (not np.allclose(com(J, real[4]), 0)) and (not np.allclose(com(J, real[5]), 0)) and np.allclose(com(J, real[4] + real[5]), 0)
blade_swap = [S for S in blades_J if swaps_last(blade(S))]
res['blade_complex_structures_with_same_fusion'] = len(blade_swap)
res['blade_complex_structure_grades'] = sorted({len(S) for S in blade_swap})
# overlap of the two linear sectors
L_om2 = nullspace_commuting([om2])
Lo, Lo2 = rank(L_om), rank(L_om2)
inter = Lo + Lo2 - rank(L_om + L_om2)
res['linear_sector_dims'] = [Lo, Lo2]; res['linear_sectors_intersection_real_dim'] = inter; res['linear_sectors_span_real_dim'] = rank(L_om + L_om2)
# matter part (off-diagonal) of each
def offdiag(Lb): return [Q[b] @ X @ Q[a] for X in Lb for a in range(5) for b in range(5) if a != b]
M1, M2 = offdiag(L_om), offdiag(L_om2)
res['matter_dims'] = [rank(M1), rank(M2)]; res['matter_intersection_real_dim'] = rank(M1) + rank(M2) - rank(M1 + M2); res['matter_span_real_dim'] = rank(M1 + M2)
# the gauge algebra of omega' and whether it equals Delta_SM
delta2 = []
for i in range(4):
    for X in L_om2:
        Y2 = Q[i] @ X @ Q[i]
        if np.linalg.norm(Y2) > 1e-9: delta2.append(Y2)
delta2.append(Q[4]); res['gauge_algebra_same_for_omega_prime'] = bool(rank(delta2) == dD and rank(delta_basis + delta2) == dD)
# omega' versus omega on the commutant: omega' is in the commutant of the gauge algebra?
res['omega_prime_in_gauge_commutant'] = bool(all(np.allclose(com(om2, d), 0) for d in delta_basis))
res['omega_prime_in_gauge_algebra'] = bool(rank(delta_basis + [om2]) == dD)
# the group generated by omega and omega' on the blocks: how many distinct complex phases on each complex block
phase = []
for q in Q:
    ratio = (om2 @ q) @ np.linalg.pinv(om @ q)
    phase.append(sorted({int(round(np.trace(q @ D @ q) / max(1, tr(q))))}))
res['omega_prime_over_omega_on_blocks_trace_sign'] = phase
json.dump(res, open('family_results.json', 'w'), indent=1, default=str)
print(json.dumps(res, indent=1, default=str))

# ======================================================================================================================
# ---- 4. complements that decide the question
# (4a) every complex structure J on V that commutes with the gauge algebra and keeps the Peirce blocks:  on a complex block the commutant of Delta_SM is C = {a + b*omega}, so J = +-omega there
#      (16 sign patterns up to an overall sign; on the last block the commutant is M2(R), J is any rotation-type element but its bookkeeping is the same).  Bookkeeping per pattern through the threegen engine.
sys.path.insert(0, 'selfcheck')
import threegen_selfcheck as tg
from fractions import Fraction as Fr
def flip(b): return (tg.DUAL[b[0]], b[1], -b[2])
pat = []
for signs in itertools.product((1, -1), repeat=4):
    sg = list(signs) + [1]
    J = sum(s * om @ q for s, q in zip(sg, Q))
    assert np.allclose(J @ J, -I16) and all(np.allclose(com(J, d), 0) for d in delta_basis)
    W = [b if s == 1 else flip(b) for b, s in zip(tg.FUREY_W, sg)]
    assert all(tg.sm_ok(b) for b in W) and tg.charge_check(W)
    lin, anti = tg.sectors(W, off_diagonal=True)
    pat.append({'signs_on_blocks_0_to_3': list(signs), 'generations': tg.generations(W), 'exotic_complex_dim': tg.exotic_dim(W), 'is_omega': signs == (1, 1, 1, 1), 'is_omega_prime': bool(np.allclose(J, om2) or np.allclose(J, -om2))})
res['gauge_compatible_complex_structures'] = len(pat)
res['their_generation_counts'] = dict(sorted({str(k): v for k, v in __import__('collections').Counter(p['generations'] for p in pat).items()}.items()))
res['their_max_generations'] = max(p['generations'] for p in pat)
res['their_patterns'] = pat
om_prime_entry = [p for p in pat if p['is_omega_prime']]
assert len(om_prime_entry) == 1
res['omega_prime_signs_on_blocks_0_to_3'] = om_prime_entry[0]['signs_on_blocks_0_to_3']
# (4b) of the 8 blade complex structures omega*t found in the Witt torus, how many commute with the gauge algebra
tor_J = []
for t in T:
    for s in (1,):
        Jc = om @ t
        if np.allclose(Jc @ Jc, -I16) and all(np.allclose(com(Jc, q), 0) for q in Q) and not any(np.allclose(Jc, X) or np.allclose(Jc, -X) for X in tor_J): tor_J.append(Jc)
res['torus_complex_structures'] = len(tor_J)
res['torus_complex_structures_commuting_with_gauge'] = sum(1 for Jc in tor_J if all(np.allclose(com(Jc, d), 0) for d in delta_basis))
# (4c) real subspace of each Standard Model edge for omega and for omega': which are the same subspace
def lin_edge(Lbasis, s, t):
    sp = [Q[t] @ X @ Q[s] for X in Lbasis]; return [M for M in sp if np.linalg.norm(M) > 1e-9]
same = {}
for nme, (s, t) in sm_edges.items():
    A1, A2 = lin_edge(L_om, s, t), lin_edge(L_om2, s, t)
    r1, r2, r12 = rank(A1), rank(A2), rank(A1 + A2)
    same[nme] = {'real_dim_omega': r1, 'real_dim_omega_prime': r2, 'shared': r1 + r2 - r12}
res['sm_edges_omega_vs_omega_prime'] = same
res['sm_edges_identical_for_both'] = [n for n, d in same.items() if d['shared'] == d['real_dim_omega'] == d['real_dim_omega_prime']]
res['sm_edges_different'] = [n for n, d in same.items() if d['shared'] != d['real_dim_omega']]
# (4d) what the gauge-commutant (12 real dimensions: complex scalars on blocks 0-3, M2(R) on the last block) does to each Standard Model edge.
#      closure = smallest commutant-invariant real space containing the edge.
def closure(B):
    cur = list(B)
    while True:
        new = cur + [com(X, M) for X in cent for M in cur]
        if rank(new) == rank(cur): return rank(cur)
        # keep an independent set
        cur = indep_fast(new)
def indep_fast(Ms):
    A = np.array([M.reshape(-1) for M in Ms]); u, s_, vt = np.linalg.svd(A, full_matrices=False); r = int(np.sum(s_ > 1e-9))
    return [vt[i].reshape(16, 16) for i in range(r)]
acts = {}
for nme, (s_, t_) in sm_edges.items():
    B = indep_fast(edges[(s_, t_)]); d0 = len(B); assert d0 == rank(B); cl = closure(B)
    # is the action on the edge a complex scalar (span of identity and left-multiplication by omega)?
    Bm = np.array([M.reshape(-1) for M in B]).T
    def co(M): return np.linalg.lstsq(Bm, M.reshape(-1), rcond=None)[0]
    inside = all(np.allclose(Bm @ co(com(X, M)), com(X, M).reshape(-1), atol=1e-8) for X in cent for M in B)
    scal = None
    if inside:
        left = np.array([co(om @ M) for M in B]).T
        scal = all(np.linalg.matrix_rank(np.array([np.eye(len(B)).reshape(-1), left.reshape(-1), np.array([co(com(X, M)) for M in B]).T.reshape(-1)]), tol=1e-8) == 2 for X in cent)
    touches_last = 4 in (s_, t_)
    acts[nme] = {'real_dim': d0, 'closure_real_dim': cl, 'preserved_by_commutant': bool(inside), 'complex_scalars_only': scal, 'touches_last_block': touches_last}
res['commutant_action_on_sm_edges'] = acts
assert all(acts[n]['preserved_by_commutant'] and acts[n]['complex_scalars_only'] for n in ('Q_L', 'u_R', 'L'))
assert all(not acts[n]['preserved_by_commutant'] and acts[n]['closure_real_dim'] == 2 * acts[n]['real_dim'] for n in ('d_R', 'e_R', 'nu_R'))
# (4e) Z3 inside the commutant: it exists, and what it does
ph = np.cos(2 * np.pi / 3) * I16 + np.sin(2 * np.pi / 3) * om
res['cube_root_phase_in_commutant'] = bool(np.allclose(ph @ ph @ ph, I16) and all(np.allclose(com(ph, d), 0) for d in delta_basis))
assert res['cube_root_phase_in_commutant']
# it acts on every Standard Model edge between blocks i, j by conjugation as the scalar exp(0) = 1 (same phase on both blocks), i.e. trivially; a block-dependent Z3 phase acts as a character, not as a permutation
res['z3_global_phase_acts_trivially_on_edges'] = bool(all(np.allclose(ph @ M @ np.linalg.inv(ph), M) for nme_, (s_, t_) in sm_edges.items() for M in edges[(s_, t_)][:20]))
assert res['z3_global_phase_acts_trivially_on_edges']
# ---- final assertions: the numbers quoted in the report
assert res['torus_group_order'] == 32 and res['torus_degrees'] == 16
assert res['torus_elements_commuting_with_gauge'] == 4 and res['torus_elements_inside_gauge_algebra'] == 16
assert res['degrees_touched_by_one_generation'] == 14
assert res['frame_symmetries_preserving_blocks'] == 16 and res['order_histogram'] == {'1': 1, '2': 11, '4': 4} and res['order3_elements'] == 0
assert res['omega_prime_in_gauge_commutant'] and not res['omega_prime_in_gauge_algebra'] and res['gauge_algebra_same_for_omega_prime']
assert res['torus_complex_structures'] == 8 and res['torus_complex_structures_commuting_with_gauge'] == 2
assert res['gauge_compatible_complex_structures'] == 16 and res['their_generation_counts'] == {'0': 4, '1': 10, '2': 2} and res['their_max_generations'] == 2
assert res['omega_prime_signs_on_blocks_0_to_3'] == [1, -1, -1, -1]
assert res['sm_edges_identical_for_both'] == ['Q_L', 'u_R', 'L', 'nu_R'] and res['sm_edges_different'] == ['d_R', 'e_R']
assert res['matter_dims'] == [96, 96] and res['matter_intersection_real_dim'] == 48 and res['matter_span_real_dim'] == 144
json.dump(res, open('family_results.json', 'w'), indent=1, default=str)
print('ALL FAMILY ASSERTIONS PASS')
print(json.dumps({k: res[k] for k in ['gauge_compatible_complex_structures', 'their_generation_counts', 'their_max_generations', 'omega_prime_signs_on_blocks_0_to_3', 'torus_complex_structures', 'torus_complex_structures_commuting_with_gauge', 'sm_edges_omega_vs_omega_prime', 'sm_edges_identical_for_both', 'sm_edges_different', 'commutant_action_on_sm_edges']}, indent=1))
print([ (p['signs_on_blocks_0_to_3'], p['generations'], p['exotic_complex_dim']) for p in pat])
